Repository nextcloud/richdocuments, pull requests merged in 2018-10, with the labels that each got.

#272 Do not use deprectaed OC.webroot
  appinfo/info.xml
  js/documents.js
Labels: 4. to release

#273 Better loading screen
  css/style.css
  js/documents.js
Labels: 3. to review

#282 Properly remove view entries from the array
  js/documents.js
Labels: 3. to review, bug

#281 Do not show loading screen if we need a nickname
  js/documents.js
Labels: 3. to review

#288 Parse the link to AssertURL trought he generateURL
  js/documents.js
Labels: 3. to review, bug

#289 Show display name on avatar hover
  js/documents.js
Labels: 3. to review, bug

#293 Do not show overlay if we request the nickname
  js/documents.js
Labels: 3. to review, bug
