Repository nextcloud/richdocuments, pull requests merged in 2018-12, with the labels that each got.

#322 Set proper z-index to avoid grid toggle button overlaying the iframe
  css/viewer/odfviewer.css
Labels: 3. to review, bug

#331 Reload file list after closing collabora
  js/viewer/viewer.js
Labels: 3. to review, bug

#321 Fix showing the files sidebar on Nextcloud 15
  js/viewer/viewer.js
Labels: 3. to review, bug

#323 Fetch capabilities from collabora and store them in appdata
  lib/Capabilities.php
Labels: 2. developing

#316 Use nextcloud versions sidebar tab
  css/style.css
  css/viewer/odfviewer.css
  js/documents.js
Labels: 3. to review

#255 Start of template API
  docs/templates.md
Labels: 2. developing
