Repository nextcloud/richdocuments, pull requests merged in 2019-07, with the labels that each got.

#542 Loading time improvements
  css/style.css
  css/viewer.scss
  js/documents.js
  js/viewer/viewer.js
Labels: 3. to review, enhancement

#543 Select the right elements from the admin settings
  js/admin.js
Labels: 3. to review, bug

#545 Bump version to 3.3.13
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#544 Use available public API calls and strong comparison
  lib/Controller/WopiController.php
  lib/Preview/Office.php
  lib/TokenManager.php
  templates/admin.php
Labels: 3. to review

#547 Switch to native font stack
  css/style.css
Labels: 3. to review, design

#548 Fix return type of isAvailable
  lib/Preview/Office.php
Labels: 3. to review, bug

#551 [stable-3.3] Pass though paste postmessage to mobile apps
  js/documents.js
Labels: 4. to release
