Repository nextcloud/richdocuments, pull requests merged in 2019-01, with the labels that each got.

#346 Fix issues with capabilities
  js/viewer/viewer.js
  lib/Capabilities.php
Labels: 3. to review, bug

#347 Fix travis running master server only on PHP>7.0
  .travis.yml
Labels: 3. to review

#339 Improve current editor listing in Nextcloud header
  css/viewer/odfviewer.scss
  js/documents.js
  templates/admin.php
Labels: 3. to review, enhancement

#364 Use templates shipped with richdocuments for new files
  appinfo/app.php
Labels: 3. to review

#370 Better wording for the image file picker
  js/documents.js
Labels: 4. to release, enhancement

#357 Pass proper response to registerFilesMenu
  js/viewer/viewer.js
Labels: 3. to review, bug

#356 Restore public page when closing collabora
  js/viewer/viewer.js
Labels: 3. to review, bug

#369 Add file actions menu to the header bar
  css/viewer/odfviewer.scss
  js/documents.js
  js/viewer/viewer.js
  lib/Controller/DocumentController.php
Labels: 3. to review, enhancement

#368 Add new file dialog on UI_CreateFile
  js/documents.js
  js/viewer/viewer.js
Labels: 3. to review, enhancement

#344 convert nextcloud locale to BCP47 languages tag correctly
  js/documents.js
Labels: 3. to review
