Repository nextcloud/richdocuments, pull requests merged in 2019-02, with the labels that each got.

#380 Use the proper old templates
  appinfo/app.php
  assets/template.odp
  assets/template.ods
  assets/template.odt
Labels: bug

#383 Use proper string for document template selection
  js/documents.js
Labels: 3. to review, bug

#382 Check if loading the document is sucessful
  js/viewer/viewer.js
Labels: 3. to review, bug

#384 Fix scrolling behaviour on Nextcloud >= 14
  css/viewer/odfviewer.scss
  js/viewer/viewer.js
Labels: 3. to review, bug

#385 Use first template by default
  js/viewer/viewer.js
Labels: 3. to review, bug

#379 Move fetching the capabilities to a backgroundjob
  appinfo/info.xml
  lib/Backgroundjobs/ObtainCapabilities.php
  lib/Capabilities.php
  lib/Controller/SettingsController.php
  lib/Service/CapabilitiesService.php
Labels: enhancement

#396 Scale frame to 100% height on mobile
  css/mobile.css
Labels: 3. to review, bug

#394 Use stored filemodel
  js/documents.js
Labels: 3. to review, bug

#392 Check before trying to call the parent reload
  js/documents.js
Labels: 3. to review, bug, high

#395 Hide sidebar when closing the viewer
  css/style.css
  js/documents.js
Labels: 3. to review, bug

#393 Fix IE11
  js/viewer/viewer.js
Labels: 3. to review, bug

#399 Remove unused handlebar templates
  Makefile
  js/templates.js
  js/templates/revHistoryContainer.handlebars
  js/templates/revHistoryItem.handlebars
Labels: 3. to review

#400 Move to single viewer css file
  appinfo/app.php
  css/viewer.scss
Labels: 3. to review

#398 Release 3.2.1
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3. to review

#405 Fix relative path of document type icons
  css/viewer.scss
Labels: 3. to review, bug

#411 allow nextcloud in an iframe
  js/documents.js
Labels: 3. to review

#412 Properly check if fileList is available
  js/documents.js
Labels: 3. to review, bug

#407 Fixes #381: use language instead of locale
  js/documents.js
Labels: 3. to review, bug

#416 Properly access files list
  js/documents.js
Labels: 3. to review, bug

#414 Add option to disable certificate validation
  js/admin.js
  lib/Controller/SettingsController.php
  lib/Preview/Office.php
  lib/Service/CapabilitiesService.php
  lib/WOPI/DiscoveryManager.php
  templates/admin.php
Labels: 3. to review, enhancement

#418 Allow to uncheck follow current user
  js/documents.js
Labels: 3. to review, bug
