Repository nextcloud/richdocuments, pull requests merged in 2019-05, with the labels that each got.

#470 Nextcloud version bump and code cleanup
  appinfo/database.xml
  appinfo/info.xml
  js/documents.js
  js/viewer/viewer.js
  lib/Preview/Office.php
Labels: 3. to review, enhancement

#480 Set timeout in case of editor inactivity
  js/documents.js
Labels: 2. developing, bug

#489 Bump version to 3.3.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#490 add txt mimetype to optional
  lib/Capabilities.php
Labels: 4. to release, enhancement

#491 Add proper fallback value for hideDownload
  lib/TokenManager.php
Labels: 3. to review, bug

#493 Use valid HTTP status codes
  lib/Controller/SettingsController.php
Labels: 3. to review, bug

#494 Bump version to 3.3.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release

#501 Fix searching for groups
  lib/TokenManager.php
Labels: 3. to review, bug

#502 Bump version to 3.3.3
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release

#505 Fix guest avatars
  js/documents.js
  lib/Controller/DocumentController.php
  lib/Controller/WopiController.php
  lib/TokenManager.php
Labels: 3. to review, bug

#507 Add logging to WOPI Controller and preview providers
  lib/Controller/WopiController.php
  lib/Preview/Office.php
Labels: 3. to review

#506 Fix preview generation on object storage
  lib/Preview/Office.php
Labels: 2. developing, bug

#508 Bump version to 3.3.4
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#510 Only allow closing other views with write permissions
  js/documents.js
Labels: 3. to review, bug

#512 Update empty presentation template
  appinfo/info.xml
  assets/presentation.otp
  lib/Migration/UpdateEmptyTemplates.php
  lib/TemplateManager.php
Labels: 3. to review

#520 Allow UTF8 characters in filenames
  lib/Controller/OCSController.php
Labels: 3. to review, bug

#519 Allow accessing the Save As web UI on mobile
  js/documents.js
Labels: 3. to review, bug

#521 Implement new Views_List message
  js/documents.js
Labels: 3. to review, enhancement

#522 Bump version to 3.3.7
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#527 Allow ms office templates
  lib/TemplateManager.php
Labels: 3. to review, bug

#524 Implement proper file renaming
  js/documents.js
  js/viewer/viewer.js
  lib/Controller/WopiController.php
Labels: 3. to review, enhancement

#525 Fix rescaling of UI in Safari
  css/mobile.css
  css/style.css
  js/documents.js
  js/viewer/viewer.js
Labels: 3. to review, bug
