Repository nextcloud/richdocuments, pull requests merged in 2019-08, with the labels that each got.

#559 Add postgres/mysql to travis
  .travis.yml
Labels: 3. to review

#557 Check the editor folder only if available
  lib/TokenManager.php
Labels: 3. to review, backport-request, bug

#562 [stable-3.3] Add check to only open one document at a time
  js/viewer/viewer.js
Labels: 3. to review, bug

#558 Add allowedFormAction csp
  appinfo/app.php
Labels: 3. to review

#573 [stable-3.3] System template upload enhancements
  js/admin.js
  lib/Controller/TemplatesController.php
  lib/TemplateManager.php
Labels: 3. to review, bug

#574 System template upload enhancements
  lib/Controller/TemplatesController.php
  lib/TemplateManager.php
  src/admin.js
Labels: 3. to review, bug

#483 Add new config item public_wopi_url.
  appinfo/app.php
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentController.php
  lib/Controller/SettingsController.php
Labels: 3. to review

#575 Fallback to regular wopi url if the public_wopi_url is not set
  appinfo/app.php
Labels: 3. to review, bug

#539 Federated document editing
  appinfo/app.php
  appinfo/database.xml
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentController.php
  lib/Controller/FederationController.php
  lib/Controller/OCSController.php
  lib/Controller/WopiController.php
  lib/Db/Wopi.php
  lib/Db/WopiMapper.php
  lib/Service/FederationService.php
  lib/TokenManager.php
  src/document.js
  src/view/FilesAppIntegration.js
  src/viewer.js
Labels: 3. to review

#580 Cleanup public wopi URL since otherwise it doesn't work in the CSP headers
  lib/Controller/SettingsController.php
Labels: 3. to review, bug

#586 Directly open document when only one template is available
  src/viewer.js
Labels: 3. to review, enhancement

#585 Fix avatar listing and console error
  src/services/postMessage.tsx
  src/view/FilesAppIntegration.js
Labels: 4. to release, bug

#569 Watermark support
  appinfo/routes.php
  lib/AppConfig.php
  lib/Controller/SettingsController.php
  lib/Controller/WopiController.php
  lib/Settings/Admin.php
  package-lock.json
  package.json
  src/admin.js
  src/components/AdminSettings.vue
  src/components/SettingsCheckbox.vue
  src/components/SettingsInputText.vue
  src/components/SettingsSelectGroup.vue
  src/components/SettingsSelectTag.vue
  src/viewer.js
  templates/admin.php
Labels: 4. to release, enhancement

#587 Prepare 3.4.0-beta1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
