Repository nextcloud/richdocuments, pull requests merged in 2019-12, with the labels that each got.

#695 Force read operation to trigger audit log when issuing a token
  lib/TokenManager.php
Labels: 3. to review, enhancement

#740 Introduce a user scope service to properly perform actions
  lib/Controller/AssetsController.php
  lib/Controller/WopiController.php
  lib/Service/UserScopeService.php
Labels: 3. to review, bug

#514 Start with new template creation mechanism
  appinfo/database.xml
  appinfo/info.xml
  appinfo/routes.php
  lib/Capabilities.php
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentController.php
  lib/Controller/WopiController.php
  lib/Db/Direct.php
  lib/Db/Wopi.php
  lib/Db/WopiMapper.php
  lib/Preview/Office.php
  lib/Service/CapabilitiesService.php
  lib/TokenManager.php
Labels: 3. to review, enhancement

#741 Move empty template update to occ command
  appinfo/info.xml
  lib/Command/UpdateEmptyTemplates.php
Labels: 3. to review, enhancement

#742 fix cache set typo
  lib/Service/FederationService.php
Labels: 4. to release, bug
