Repository nextcloud/richdocuments, pull requests merged in 2019-10, with the labels that each got.

#653 Lower log level if the token does not exist
  lib/Controller/WopiController.php
Labels: 3. to review, bug

#651 Move file list access to files app integration
  src/view/FilesAppIntegration.js
  src/viewer.js
Labels: 3. to review, bug

#645 Check key before accessing
  lib/AppConfig.php
Labels: 3. to review, bug

#652 Fix undefined index warning
  lib/Controller/WopiController.php
  templates/documents.php
Labels: 3. to review, bug

#670 Do not use template shipped by core
  lib/Controller/DocumentController.php
Labels: 3. to review, technical debt

#671 Always open CSV files with collabora
  lib/Capabilities.php
Labels: 3. to review

#676 Small bugfixes with public page loading, IE11 and avatar colors
  src/document.js
  src/helpers/guestName.js
  src/services/postMessage.tsx
  src/view/FilesAppIntegration.js
  templates/documents.php
Labels: 3. to review, bug
