Repository nextcloud/richdocuments, pull requests merged in 2019-11, with the labels that each got.

#672 Bump release to 3.4.3
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#683 Yet another fix for the file list handling
  src/viewer.js
Labels: 3. to review, bug

#694 Retry putContent operation if locked
  lib/Controller/WopiController.php
Labels: 3. to review, bug

#700 Always use the owner file owner to access for share links
  lib/Controller/WopiController.php
  lib/TokenManager.php
Labels: 3. to review, bug

#699 Make sure files created from the same template have a different WOPI file id
  appinfo/routes.php
  lib/Controller/DocumentController.php
  lib/Helper.php
Labels: 3. to review, bug, high

#701 Admin resources in app store should point to Github repo
  appinfo/info.xml
Labels: 3. to review, enhancement

#713 Make sure Firefox doesn't navigate out of the current directory
  src/viewer.js
Labels: 3. to review, bug

#712 Include locale in the loleaflet lang parameter
  src/helpers/index.js
Labels: 3. to review, bug
