Repository nextcloud/richdocuments, pull requests merged in 2019-04, with the labels that each got.

#459 Check actual file if it can be updated
  lib/TokenManager.php
Labels: 3. to review, bug

#465 Use error instead of exception template
  lib/Controller/DocumentController.php
Labels: 3. to review, bug

#474 Remove tests for old stable branches
  .travis.yml
Labels: 3. to review

#473 Hide user list on desktop
  lib/Controller/WopiController.php
Labels: 3. to review, bug

#460 Add list tof supported mimetypes to capabilities
  js/viewer/viewer.js
  lib/Capabilities.php
Labels: 3. to review

#471 Use collabora for PDF previews
  lib/AppInfo/Application.php
  lib/Preview/Pdf.php
Labels: 3. to review, enhancement

#472 Provide ooxml file extensions when set in templates
  lib/TemplateManager.php
Labels: 3. to review, bug

#475 Implement hide download support for public shares
  appinfo/database.xml
  appinfo/info.xml
  lib/Controller/WopiController.php
  lib/Db/Wopi.php
  lib/Db/WopiMapper.php
  lib/TokenManager.php
Labels: 3. to review, enhancement

#478 Use product name in file action label
  js/viewer/viewer.js
Labels: 3. to review, bug
