Repository nextcloud/richdocuments, pull requests merged in 2020-09, with the labels that each got.

#1055 Fix bug #1054
  lib/Migration/Version030702Date20200626072306.php
  lib/Migration/Version2060Date20200302132145.php
Labels: 2. developing

#1133 Use proper base template to be compatible with Nextcloud 20
  lib/Controller/DocumentController.php
Labels: 3. to review, bug

#1134 Bump version to 3.7.4
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#1137 Ebardie/activate config
  appinfo/info.xml
  docs/install.md
  lib/Command/ActivateConfig.php
Labels: 4. to release, enhancement

#1153 Very minimal document templates for Collabora Online
  assets/document.ott
  assets/docxtemplate.docx
  assets/odttemplate.odt
  assets/pptxtemplate.pptx
  assets/presentation.otp
  assets/spreadsheet.ots
  assets/template.odp
  assets/template.ods
  assets/template.odt
  assets/xlsxtemplate.xlsx
Labels: 4. to release

#1150 arm64: Allow auto-enabling Built-in CODE Server on ARM64
  lib/AppInfo/Application.php
Labels: 4. to release, enhancement

#1152 Properly check value types when updating watermark settings
  lib/Controller/SettingsController.php
Labels: 3. to review, bug

#1162 Arm64 adaptations
  lib/Service/CapabilitiesService.php
  src/components/AdminSettings.vue
  src/document.js
Labels: 3. to review, bug

#1164 Do not use isset for checking the class constant
  lib/Controller/SettingsController.php
Labels: 3. to review, bug

#1170 No need to get the avatar image since we have one for each user
  lib/Controller/WopiController.php
Labels: 3. to review, performance
