Repository nextcloud/richdocuments, pull requests merged in 2020-10, with the labels that each got.

#1192 Lint fix
  src/files.js
Labels: 3. to review

#1049 Move to github actions
  .drone.yml
  .github/workflows/lint.yml
  .github/workflows/nodejs.yml
  .gitignore
  .travis.yml
  composer.json
Labels: 2. developing

#974 Add frontend hooks and expose config/open methods
  css/viewer.scss
  docs/frontend-integration.md
  lib/Controller/DocumentController.php
  lib/Controller/FederationController.php
  lib/Controller/WopiController.php
  lib/Events/BeforeFederationRedirectEvent.php
  lib/Service/FederationService.php
  src/document.js
  src/files.js
  src/helpers/guestName.js
  src/helpers/index.js
  src/helpers/url.js
  src/services/preload.js
  src/view/FilesAppIntegration.js
  src/view/NewFileMenu.js
  templates/documents.php
Labels: 3. to review, enhancement

#1194 Use base template for direct editing
  lib/Controller/DirectViewController.php
Labels: 3. to review, bug
