Repository nextcloud/richdocuments, pull requests merged in 2020-11, with the labels that each got.

#1210 Fix escaping for edit with message
  src/files.js
Labels: 3. to review, bug

#1211 Passing some UI Defaults to loleaflet frame
  src/document.js
Labels: 3. to review, enhancement

#1220 Fix #1219 - add 'application/vnd.ms-visio.drawing' to support .vsdx
  lib/Capabilities.php
Labels: 4. to release, enhancement

#1222 Adjust ui_defaults
  src/document.js
Labels: 3. to review, bug

#1226 Move Collabora endpoint caching to distributed cache
  lib/AppInfo/Application.php
  lib/Backgroundjobs/ObtainCapabilities.php
  lib/Capabilities.php
  lib/Command/ActivateConfig.php
  lib/Controller/SettingsController.php
  lib/Service/CapabilitiesService.php
  lib/WOPI/DiscoveryManager.php
Labels: 3. to review, enhancement

#1221 Add close method and document public documentsMain methods
  src/document.js
Labels: 3. to review, bug

#1237 Make frame loading timeout configurable
  lib/AppConfig.php
  lib/Capabilities.php
  src/files.js
Labels: 3. to review, enhancement

#1238 Move to @nextcloud/capabilities and only register default mime types for viewer
  package-lock.json
  package.json
  src/components/AdminSettings.vue
  src/files.js
  src/helpers/types.js
  src/view/NewFileMenu.js
  src/viewer.js
Labels: 3. to review, bug

#1240 Add two more useful placeholders for watermark text
  lib/Controller/WopiController.php
  src/components/AdminSettings.vue
Labels: 4. to release, enhancement

#1239 Fix compatibility to oracle as a database
  .drone.yml
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  .github/workflows/nodejs.yml
  .github/workflows/phpunit.yml
  lib/Controller/WopiController.php
  lib/Db/Wopi.php
  lib/Migration/Version2060Date20200302131958.php
  lib/Migration/Version30704Date20200626072306.php
  lib/Migration/Version30709Date20201111104147.php
  lib/TokenManager.php
  tests/run-integration.sh
Labels: 4. to release, bug

#1244 Do not fail if capabilities have not been fetched for the built-in server
  lib/Service/CapabilitiesService.php
Labels: 3. to review, bug

#1243 Add migration to bigint columns
  appinfo/info.xml
  lib/Command/ConvertToBigInt.php
  lib/Migration/Version2060Date20200302131958.php
  lib/Migration/Version2060Date20200302132145.php
  lib/Migration/Version30704Date20200626072306.php
Labels: 3. to review, bug

#1258 Revert "Move to @nextcloud/capabilities"
  src/components/AdminSettings.vue
  src/files.js
  src/helpers/types.js
  src/view/NewFileMenu.js
Labels: 3. to review, bug

#1257 Try to obtain the appdata folder in 1 go
  lib/TemplateManager.php
Labels: 3. to review, enhancement

#1266 Fix issues with federated editing in global scale setups
  lib/AppInfo/Application.php
  lib/Service/FederationService.php
  src/document.js
Labels: 3. to review, bug
