Repository nextcloud/richdocuments, pull requests merged in 2020-06, with the labels that each got.

#1010 Advise installation via 'occ' if it fails from the web interface.
  src/components/AdminSettings.vue
Labels: 4. to release, enhancement

#1017 Handling of a new error state from proxy.php?status.
  src/document.js
Labels: enhancement

#1020 Check for read permission on the file actions
  src/files.js
Labels: 3. to review, bug

#885 Move to @nextcloud packages
  package-lock.json
  package.json
  src/admin.js
  src/components/AdminSettings.vue
  src/components/SettingsSelectGroup.vue
  src/components/SettingsSelectTag.vue
  src/document.js
  src/helpers/guestName.js
  src/helpers/index.js
  src/helpers/url.js
Labels: 3. to review, dependencies

#1038 Fix issues with Nextcloud 15/16
  lib/AppInfo/Application.php
Labels: 3. to review, bug

#1036 Fix problem where mobile.css did not get used for subsequent document edits
  src/files.js
Labels: 4. to release

#1039 Bump version to 3.7.1
  CHANGELOG.md
  appinfo/info.xml
  lib/PermissionManager.php
  tests/lib/PermissionManagerTest.php
  tests/phpunit.xml
Labels: 3. to review

#1052 getCurrentUser might be null in contrast to OC.getCurrentUser
  src/helpers/guestName.js
Labels: 3. to review, bug, high

#1023 Fix saving 'disable certificate verification'
  lib/Controller/SettingsController.php
Labels: 2. developing

#1059 Pick up trusted certificates again
  lib/Controller/SettingsController.php
  lib/Preview/Office.php
  lib/Service/CapabilitiesService.php
  lib/Settings/Admin.php
  lib/WOPI/DiscoveryManager.php
Labels: 3. to review, bug

#1061 Check for the proper current user value (again)
  src/helpers/guestName.js
Labels: 3. to review, bug
