Repository nextcloud/richdocuments, pull requests merged in 2020-05, with the labels that each got.

#932 Save As Dialog Input Width Will Be Increased For Better Usage #931
  src/document.js
Labels: 3. to review, design

#922 Add details popover for the demo servers
  src/components/AdminSettings.vue
Labels: 4. to release, enhancement

#815 Bump 3.6.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#961 Use babel to make typescript files compatible with IE11
  webpack.common.js
Labels: 3. to review, bug

#959 Disable certificate verification handling
  lib/Controller/SettingsController.php
  lib/Preview/Office.php
  lib/Service/CapabilitiesService.php
  lib/WOPI/DiscoveryManager.php
Labels: 4. to release, bug

#958 Resolves: check for obvious sillies #954
  src/components/AdminSettings.vue
Labels: 2. developing, enhancement

#976 Be more robust on paths that don't start with a slash
  lib/Controller/OCSController.php
Labels: 3. to review, bug

#973 Move css to the bundles
  appinfo/app.php
  css/admin.scss
  css/document.scss
  css/templatePicker.scss
  css/viewer.scss
  img/x-office-document.svg
  img/x-office-presentation.svg
  img/x-office-spreadsheet.svg
  src/admin.js
  src/document.js
  src/personal.js
  src/viewer.js
  templates/admin.php
  templates/documents.php
  templates/personal.php
  templates/public.php
Labels: 4. to release, technical debt

#975 Expose config without extra http call
  lib/Capabilities.php
  src/helpers/types.js
  src/viewer.js
Labels: 3. to review, enhancement

#977 l10n: Change uppercase letter to lowercase
  src/components/AdminSettings.vue
Labels: design

#980 Avoid duplicate save request
  src/components/AdminSettings.vue
Labels: bug

#978 Admin Settings: Add option to enable built-in CODE server
  src/components/AdminSettings.vue
Labels: 4. to release, enhancement

#979 Add viewer integration
  appinfo/app.php
  lib/AppInfo/Application.php
  lib/Controller/DocumentController.php
  package-lock.json
  package.json
  src/files.js
  src/view/FilesAppIntegration.js
  src/view/Office.vue
  src/viewer.js
  templates/documents.php
  webpack.common.js
Labels: 3. to review, enhancement

#986 Allow connecting to local addresses
  .drone.yml
  lib/Service/CapabilitiesService.php
  lib/WOPI/DiscoveryManager.php
Labels: 3. to review, bug

#988 Document templates: use only one sans-serif font family
  assets/docxtemplate.docx
  assets/pptxtemplate.pptx
  assets/template.odp
  assets/template.ods
  assets/template.odt
  assets/xlsxtemplate.xlsx
Labels: 3. to review, design, enhancement

#987 Built-In CODE Server status message on first load
  css/document.scss
  src/document.js
  templates/documents.php
Labels: 4. to release, enhancement

#992 Increase /hosting/discovery and /hosting/capabilities timeouts.
  lib/Service/CapabilitiesService.php
  lib/WOPI/DiscoveryManager.php
Labels: 4. to release, enhancement

#994 Platform and OS checks for the built-in server option
  lib/Settings/Admin.php
  src/components/AdminSettings.vue
Labels: 3. to review, enhancement

#995 Set an empty default url
  lib/AppConfig.php
Labels: 3. to review, bug

#998 Re-fetch the proxy status when there is a problem + show a helpful message.
  src/document.js
Labels: 3. to review, enhancement

#999 Do not check for capabilities during load though proxy
  src/files.js
Labels: 3. to review, bug
