Repository nextcloud/richdocuments, pull requests merged in 2021-03, with the labels that each got.

#1394 Improve dark theme experience
  src/document.js
Labels: 3. to review

#1401 Assets: Use octet-stream and attachment instead of allowing to inline display
  lib/Controller/AssetsController.php
Labels: 3. to review, backport-request, bug

#1374 Make sure that the same host remote is always considered as trusted
  lib/Service/FederationService.php
Labels: 3. to review, backport-request, bug

#1397 Emit events on frontend states
  package-lock.json
  package.json
  src/document.js
  src/files.js
  src/view/FilesAppIntegration.js
Labels: 3. to review, backport-request, enhancement

#1414 Add docs and sharingToken to the events
  docs/frontend-integration.md
  src/document.js
  src/files.js
  src/view/FilesAppIntegration.js
Labels: 3. to review, bug

#1412 Trim duplicate trailing slashes in wopi url
  lib/Service/CapabilitiesService.php
  lib/WOPI/DiscoveryManager.php
Labels: 3. to review, backport-request, bug

#1413 [stable3.7] Emit events on frontend failure states
  docs/frontend-integration.md
  package-lock.json
  package.json
  src/document.js
  src/files.js
  src/view/FilesAppIntegration.js
Labels: 3. to review, bug, enhancement

#1416 Pass through UI_Share message if used in the version viewer
  src/document.js
  src/view/FilesAppIntegration.js
Labels: 3. to review, backport-request, bug

#1417 [stable3.7] Fix version restore
  src/view/FilesAppIntegration.js
Labels: 3. to review, bug

#1423 Manual translations backport
  l10n/es_AR.js
  l10n/es_AR.json
  l10n/nl.js
  l10n/nl.json
  l10n/sc.js
  l10n/sc.json
  l10n/si.js
  l10n/si.json
  l10n/ta.js
  l10n/ta.json
  l10n/zh_HK.js
  l10n/zh_HK.json
Labels: 3. to review, bug

#1422 Properly handle ooxml with the new template mechanism
  lib/AppInfo/Application.php
Labels: 3. to review, bug

#1443 Use correct config for GS info
  lib/AppInfo/Application.php
Labels: 3. to review, bug

#1447 Add @nextcloud/dialogs and @nextcloud/event-bus to babel
  package-lock.json
  package.json
  webpack.common.js
Labels: 3. to review, backport-request, bug
