Repository nextcloud/richdocuments, pull requests merged in 2021-05, with the labels that each got.

#1513 Don't cache empty capabilities
  lib/Service/CapabilitiesService.php
Labels: backport-request

#1528 Emit WOPI postmessages through the nextcloud event bus
  docs/frontend-integration.md
  src/services/postMessage.tsx
Labels: 3. to review, backport-request, enhancement

#1514 Work around safari having a inproper 100vh value
  src/files.js
Labels: 3. to review, bug

#1544 Retry to check if Collabora is configured
  src/files.js
Labels: backport-request

#1546 Fix wrong parameters set when creating a file from a template id
  lib/TokenManager.php
  tests/features/bootstrap/RichDocumentsContext.php
  tests/features/bootstrap/WopiContext.php
  tests/features/wopi.feature
Labels: 3. to review, backport-request, bug

#1549 [stable3.8] Retry to check if Collabora is configured
  src/files.js
Labels: 3. to review

#1559 Fix PutRelativeFile as non-owner
  lib/Controller/WopiController.php
  tests/features/bootstrap/WopiContext.php
  tests/features/wopi.feature
Labels: 3. to review, backport-request, bug
