Repository nextcloud/richdocuments, pull requests merged in 2021-11, with the labels that each got.

#1833 Show warning message on protocol mismatch with collabora
  src/components/AdminSettings.vue
Labels: bug, 3. to review, backport-request

#1470 Basic draw support
  assets/drawing.otg
  assets/odgtemplate.otg
  css/viewer.scss
  img/x-office-drawing.svg
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Service/CapabilitiesService.php
  lib/Template/CollaboraTemplateProvider.php
  lib/TemplateManager.php
  src/files.js
Labels: enhancement, 4. to release

#1858 Update npm and node engines versions
  package.json
Labels: dependencies

#1877 Update documentation to use new cool/browser urls
  docs/install.md
Labels: 3. to review

#1867 Native avatars and branding bits
  css/viewer.scss
  lib/AppInfo/Application.php
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentController.php
  lib/Controller/WopiController.php
  lib/Service/CapabilitiesService.php
  lib/Service/InitialStateService.php
  lib/Settings/Admin.php
  lib/Settings/Personal.php
  lib/Settings/Section.php
  src/components/AdminSettings.vue
  src/files.js
  src/services/collabora.js
  src/services/postMessage.tsx
  src/view/FilesAppIntegration.js
  src/view/Office.vue
Labels: enhancement, 3. to review
