Repository nextcloud/richdocuments, pull requests merged in 2021-04, with the labels that each got.

#1448 Migrate to @nextcloud/webpack-vue-config
  .babelrc
  .eslintrc.js
  babel.config.js
  lib/AppInfo/Application.php
  package-lock.json
  package.json
  src/admin.js
  src/components/AdminSettings.vue
  src/components/SettingsCheckbox.vue
  src/components/SettingsExternalApps.vue
  src/components/SettingsInputText.vue
  src/components/SettingsSelectGroup.vue
  src/components/SettingsSelectTag.vue
  src/document.js
  src/files.js
  src/helpers/guestName.js
  src/helpers/index.js
  src/helpers/mobile.js
  src/helpers/types.js
  src/helpers/url.js
  src/personal.js
  src/services/preload.js
  src/view/FilesAppIntegration.js
  src/view/NewFileMenu.js
  src/view/Office.vue
  src/viewer.js
  templates/admin.php
  templates/documents.php
  templates/personal.php
  webpack.common.js
  webpack.dev.js
  webpack.js
  webpack.prod.js
Labels: 2. developing, dependencies, enhancement

#1446 Setup FeaturePolicy to allow fullscreen
  lib/Controller/DocumentController.php
Labels: 3. to review, backport-request, bug

#1465 Fix OOXML template extension
  lib/AppInfo/Application.php
Labels: 4. to release, bug

#1471 Fix duplicate document templates
  lib/AppInfo/Application.php
Labels: 3. to review, bug

#1488 Improve parsing of guest name cookie
  src/helpers/guestName.js
Labels: 3. to review, backport-request, bug

#1489 Improve parsing of guest name cookie
  src/helpers/guestName.js
Labels: 3. to review, bug

#1499 Add psalm
  .github/workflows/static-analysis.yml
  composer.json
  composer.lock
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review

#1502 Do not use libxml_disable_entity_loader on PHP 8 or later
  lib/WOPI/Parser.php
Labels: 3. to review, bug

#1501 Add federation/direct editing tests
  .github/workflows/integration.yml
  lib/Controller/DirectViewController.php
  tests/composer.json
  tests/composer.lock
  tests/config/behat.yml
  tests/features/bootstrap/DirectContext.php
  tests/features/bootstrap/FeatureContext.php
  tests/features/bootstrap/FederationContext.php
  tests/features/bootstrap/RichDocumentsContext.php
  tests/features/bootstrap/WopiContext.php
  tests/features/direct.feature
  tests/features/federation.feature
  tests/features/wopi.feature
  tests/run-integration.sh
Labels: 3. to review

#1512 Enhanced federated editing
  .github/workflows/integration.yml
  appinfo/routes.php
  docs/federated-editing.md
  docs/mobile_editor.md
  lib/AppInfo/Application.php
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentController.php
  lib/Controller/FederationController.php
  lib/Controller/OCSController.php
  lib/Controller/WopiController.php
  lib/Db/Direct.php
  lib/Db/DirectMapper.php
  lib/Db/Wopi.php
  lib/Db/WopiMapper.php
  lib/Migration/Version30717Date20210310164901.php
  lib/Service/FederationService.php
  lib/TokenManager.php
  src/document.js
  tests/composer.json
  tests/composer.lock
  tests/config/behat.yml
  tests/features/bootstrap/DirectContext.php
  tests/features/bootstrap/FederationContext.php
  tests/features/bootstrap/RichDocumentsContext.php
  tests/features/bootstrap/WopiContext.php
  tests/features/direct.feature
  tests/features/federation.feature
  tests/features/wopi.feature
Labels: 3. to review, enhancement
