Repository nextcloud/richdocuments, pull requests merged in 2021-01, with the labels that each got.

#1303 Cut of guest names so they fit into the database
  lib/TokenManager.php
Labels: 3. to review, bug

#1178 Show error if trying to open a file on session credential based external storage
  src/files.js
Labels: 3. to review, enhancement

#1305 Properly trim trailing slashes from the remote url
  lib/Service/FederationService.php
Labels: 3. to review, bug

#1326 Do not update CSP on calls to files_sharing
  lib/AppInfo/Application.php
Labels: 3. to review

#1327 Handle errors when fetching remote file info more gracefully
  lib/Controller/DocumentController.php
  lib/Service/FederationService.php
Labels: 3. to review, bug

#1329 Move federation cache to a distributed one
  lib/Service/FederationService.php
Labels: 3. to review
