Repository nextcloud/richdocuments, pull requests merged in 2022-08, with the labels that each got.

#2328 Limit capabilities to users that are enabled
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Listener/LoadViewerListener.php
  lib/Listener/ShareLinkListener.php
  lib/PermissionManager.php
  tests/lib/PermissionManagerTest.php
  tests/stub.phpstub
Labels: bug, 3. to review, backport-request

#2338 Fix translation string for "Loading {filename} ..."
  src/view/Office.vue
Labels: bug, 3. to review

#2335 [stable23] Allow opening PDF with Collabora
  css/filetypes.scss
  src/viewer.js
Labels: bug, 3. to review

#2336 Backport24/html encoding filename
  src/view/Office.vue
  templates/documents.php
Labels: backport-request

#2312 Do not show two header bars on public link
  src/document.js
  src/files.js
Labels: bug, 2. developing, design, backport-request

#2330 Prefer node with update permission and consolidate getting the file
  lib/Controller/WopiController.php
Labels: bug, 3. to review, backport-request

#2346 [stable23] Fix incorrect HTML encoding of filename
  src/view/Office.vue
  templates/documents.php
Labels: bug, 3. to review

#2350 Emit event for each user on document open
  lib/Controller/WopiController.php
  lib/Events/DocumentOpenedEvent.php
Labels: enhancement, 3. to review

#2351 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#2349 [stable24] Limit capabilities to users that are enabled
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Listener/LoadViewerListener.php
  lib/Listener/ShareLinkListener.php
  lib/PermissionManager.php
  tests/lib/PermissionManagerTest.php
  tests/stub.phpstub
Labels: bug, 3. to review, backport-request

#2280 Prevent download on user shares
  lib/TokenManager.php
  tests/stub.phpstub
Labels: enhancement, 3. to review, backport-request

#2356 Log error when fetching the capabilities fails
  lib/Service/CapabilitiesService.php
  lib/WOPI/DiscoveryManager.php
Labels: bug, 3. to review

#2358 Defer viewer registration
  src/viewer.js
Labels: 3. to review

#2368 Update npm and node engines versions
  package-lock.json
  package.json
Labels: dependencies

#2369 Limit avatar request size to 64 pixel
  lib/Controller/WopiController.php
Labels: 3. to review, backport-request

#2372 fix safari does not focus to document frame on startup
  src/document.js
Labels: bug, 3. to review

#2329 Remove unused registration with deprecated template manager
  lib/AppInfo/Application.php
Labels: 3. to review, technical debt

#2390 Fix: hide download option inside Collabora for "hide download" shares
  lib/TokenManager.php
Labels: bug, 3. to review

#2375 [stable22] Limit capabilities to users that are enabled
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Listener/ShareLinkListener.php
  lib/PermissionManager.php
  tests/lib/PermissionManagerTest.php
  tests/psalm-baseline.xml
Labels: bug, 4. to release

#2399 Hide "Save as" option when downloading is not allowed by share
  lib/Controller/WopiController.php
Labels: bug, 3. to review

#2401 [stable24] Updates "productName" in capabilities
  lib/Capabilities.php
Labels: bug, 4. to release

#2400 Only register templates if enabled for user
  lib/AppInfo/Application.php
Labels: bug, 3. to review, backport-request

#2402 [stable24] Hide "Save as" option when downloading is not allowed by s…
  lib/Controller/WopiController.php
Labels: bug, 3. to review
