Repository nextcloud/richdocuments, pull requests merged in 2022-10, with the labels that each got.

#2493 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2494 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2497 Migrate away from legacy mapper
  lib/Db/AssetMapper.php
  lib/Db/Direct.php
  lib/Db/DirectMapper.php
  lib/Db/Wopi.php
  lib/Db/WopiMapper.php
Labels: 3. to review, technical debt

#2490 Always enable editing for admins
  lib/PermissionManager.php
Labels: bug, 3. to review, backport-request

#2500 Add CSRF token to local edit URL
  src/document.js
Labels: bug, 4. to release, backport-request

#2468 Fix `public_wopi_url` variable configuration name
  lib/AppConfig.php
Labels: 4. to release

#2483 Cleanup frontend dev dependencies
  .eslintrc.js
  .github/workflows/lint.yml
  package-lock.json
  package.json
  src/admin.js
  src/components/AdminSettings.vue
  src/components/SettingsFont.vue
  src/components/SettingsFontList.vue
  src/components/SettingsInputFile.vue
  src/components/SettingsSelectGroup.vue
  src/components/SettingsSelectTag.vue
  src/document.js
  src/files.js
  src/helpers/filesApp.js
  src/helpers/guestName.js
  src/helpers/url.js
  src/services/api.js
  src/services/collabora.js
  src/view/FilesAppIntegration.js
  src/view/NewFileMenu.js
  src/view/Office.vue
  src/viewer.js
Labels: 3. to review

#2503 Disable sharing for public links and versions if app is disabled
  lib/Controller/WopiController.php
  src/helpers/url.js
Labels: bug, 3. to review, backport-request

#2502 Add config option to turn on Collabora feature lock for read only users
  lib/AppConfig.php
  lib/Controller/WopiController.php
  lib/PermissionManager.php
  tests/lib/PermissionManagerTest.php
Labels: enhancement, 3. to review, backport-request

#2341 add optional parameter to buy product
  src/document.js
Labels: enhancement, 2. developing

#2519 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: dependencies

#2521 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2520 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2522 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#2511 Only apply hideDownload if share attribute is actually false
  lib/TokenManager.php
Labels: bug, 3. to review, backport-request, regression

#2526 Pin postgres version
  .github/workflows/integration.yml
  .github/workflows/phpunit.yml
Labels: 3. to review

#2525 Use proper product name in capabilities
  lib/Capabilities.php
Labels: bug, 3. to review, backport-request

#2537 Return proper status code if file is not found during writing
  lib/Controller/WopiController.php
Labels: bug, 3. to review, backport-request

#2543 Do not fail if no directory is passed when creating a file from a template
  lib/Controller/OCSController.php
Labels: bug, 3. to review, backport-request

#2551 option to use new grouped saveas
  src/document.js
  src/helpers/coolParameters.js
Labels: bug, 3. to review

#2550 Keep passing light theme values to Collabora as long as the dark mode is not available there
  src/helpers/coolParameters.js
  templates/documents.php
Labels: bug, 3. to review

#2559 Invoke read permission check to trigger terms of services when creating a token
  lib/TokenManager.php
Labels: bug, 3. to review

#2560 Add app config to override wopi checkFileInfo
  lib/AppConfig.php
  lib/Controller/WopiController.php
Labels: enhancement, 3. to review, pending documentation

#2570 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2571 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2573 Fix redundant port number in url
  src/helpers/url.js
Labels: bug, 4. to release

#2588 Adjust preview event name to BeforePreviewFetchedEvent
  lib/AppInfo/Application.php
  lib/Listener/BeforeFetchPreviewListener.php
  tests/psalm-baseline.xml
Labels: bug, 3. to review

#2592 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2591 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2590 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
