Repository nextcloud/richdocuments, pull requests merged in 2022-12, with the labels that each got.

#2652 Add logging for remote requests
  lib/AppInfo/Application.php
  lib/Service/CapabilitiesService.php
  lib/WOPI/DiscoveryManager.php
Labels: backport-request

#2669 Move WOPI checks to the middleware
  lib/Controller/WopiController.php
  lib/Middleware/WOPIMiddleware.php
Labels: bug, 3. to review

#2672 [stable23] Move WOPI checks to the middleware
  lib/Controller/WopiController.php
  lib/Middleware/WOPIMiddleware.php
Labels: bug, 3. to review

#2674 [stable25] Move WOPI checks to the middleware
  lib/Controller/WopiController.php
  lib/Middleware/WOPIMiddleware.php
Labels: bug, 3. to review

#2673 [stable24] Move WOPI checks to the middleware
  lib/Controller/WopiController.php
  lib/Middleware/WOPIMiddleware.php
Labels: bug, 3. to review

#2671 [stable4] Move WOPI checks to the middleware
  lib/Controller/WopiController.php
  lib/Middleware/WOPIMiddleware.php
Labels: bug, 3. to review

#2670 [stable3.8] Move WOPI checks to the middleware
  lib/AppInfo/Application.php
  lib/Controller/WopiController.php
  lib/Middleware/WOPIMiddleware.php
Labels: bug, 3. to review

#2686 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2680 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2688 Log info message on wopi ip mismatch
  lib/Middleware/WOPIMiddleware.php
Labels: 3. to review, backport-request

#2692 Be less strict with splitting the wopi allow list
  lib/Middleware/WOPIMiddleware.php
Labels: bug, 3. to review

#2704 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2705 [stable23] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
