Repository nextcloud/richdocuments, pull requests merged in 2022-02, with the labels that each got.

#2015 Avoid too specific psalm annotation
  .github/workflows/phpunit.yml
  composer.json
  lib/Listener/FileCreatedFromTemplateListener.php
Labels: bug, 3. to review

#1977 Always add gs.trustedHosts to the CSP
  docs/federated-editing.md
  lib/AppInfo/Application.php
Labels: bug, 3. to review, backport-request

#2036 Replace deprecated OC functions by @nextcloud/* npm pkgs ones
  package-lock.json
  package.json
  src/admin.js
  src/components/AdminSettings.vue
  src/components/SettingsSelectGroup.vue
  src/files.js
  src/helpers/url.js
  src/personal.js
  src/view/FilesAppIntegration.js
  src/view/NewFileMenu.js
Labels: 3. to review, technical debt

#2031 Change wording from "New graphic" to "New diagram"
  lib/AppInfo/Application.php
Labels: enhancement, 3. to review

#2053 Do not hide speadsheet statusbar by default
  src/helpers/coolParameters.js
Labels: bug, 3. to review

#2051 🐛 Fix CSP violation when Nextcloud server has so-called 'service root'
  lib/AppInfo/Application.php
  lib/Controller/DocumentController.php
Labels: bug, 3. to review, backport-request

#2054 Map es-419 to es-MX
  src/helpers/index.js
Labels: bug, 3. to review

#2069 Adapt branding css variables
  src/helpers/coolParameters.js
Labels: bug, 3. to review, backport-request
