Repository nextcloud/richdocuments, pull requests merged in 2022-04, with the labels that each got.

#2110 Allow MS Office template file extensions for TemplateSource usage
  lib/TemplateManager.php
Labels: bug, 3. to review

#2127 fix: template.odg file must be real odg file
  emptyTemplates/template.odg
Labels: backport-request

#2131 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#2130 Created a minimal otg file
  emptyTemplates/drawing.otg
Labels: enhancement, 4. to release

#2126 Fixes CSP on Nextcloud installations not on root directory
  lib/AppInfo/Application.php
Labels: bug, 2. developing, backport-request

#2141 Let integration tests pass again
  .github/workflows/integration.yml
  tests/run-integration.sh
Labels: 3. to review, backport-request

#2149 Pass TTL token to Collabora
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentController.php
  lib/Db/WopiMapper.php
  src/document.js
  templates/documents.php
Labels: enhancement, 3. to review, collabora

#2150 Enforce token expiry on WOPI controllers
  lib/Controller/FederationController.php
  lib/Controller/OCSController.php
  lib/Controller/WopiController.php
  lib/Db/WopiMapper.php
  lib/Exceptions/ExpiredTokenException.php
  lib/Exceptions/UnknownTokenException.php
  lib/TokenManager.php
Labels: enhancement, 3. to review, collabora

#2153 Adjust template preview ratio
  lib/AppInfo/Application.php
Labels: enhancement, 3. to review, backport-request

#2142 Add gs.trustedHosts to form-action csp
  lib/AppInfo/Application.php
Labels: bug, 4. to release, backport-request

#2161 Add app config to enable trusted domain list usage
  docs/federated-editing.md
  lib/AppConfig.php
  lib/Service/FederationService.php
Labels: bug, 3. to review

#2166 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#2168 Clean up expired tokens
  lib/Backgroundjobs/Cleanup.php
  lib/Db/WopiMapper.php
Labels: enhancement, 3. to review
