Repository nextcloud/richdocuments, pull requests merged in 2022-05, with the labels that each got.

#2171 Add token_ttl app config
  lib/AppConfig.php
  lib/Db/WopiMapper.php
Labels: enhancement, 3. to review

#2172 File history fix behaviour in group folders
  lib/Controller/WopiController.php
  src/view/FilesAppIntegration.js
Labels: enhancement, 2. developing

#2032 Allow to upload fonts from the admin interface
  appinfo/routes.php
  lib/Controller/SettingsController.php
  lib/Service/FontService.php
  lib/Settings/Admin.php
  lib/UploadException.php
  src/components/AdminSettings.vue
  src/components/SettingsFont.vue
  src/components/SettingsFontList.vue
  src/components/SettingsInputFile.vue
Labels: enhancement, 2. developing, upstream: online

#2212 Use visibility instead of display to have the iframe already allocate the size
  src/view/Office.vue
Labels: bug, 3. to review

#2104 Locking
  .github/workflows/lint.yml
  appinfo/routes.php
  composer.lock
  lib/Controller/WopiController.php
Labels: enhancement, 3. to review, backport-request

#2221 Fix viewer styling to adjust to upstream viewer changes
  src/view/Office.vue
Labels: bug, 3. to review, backport-request

#1957 Emit read hook instead of fopen for admin_audit
  lib/TokenManager.php
Labels: 3. to review, backport-request, performance

#2233 Add php-cs-fixer
  .github/workflows/lint.yml
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  composer.lock
  lib/AppConfig.php
  lib/AppInfo/Application.php
  lib/Backgroundjobs/Cleanup.php
  lib/Backgroundjobs/ObtainCapabilities.php
  lib/Capabilities.php
  lib/Command/ActivateConfig.php
  lib/Command/UpdateEmptyTemplates.php
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentAPIController.php
  lib/Controller/DocumentController.php
  lib/Controller/FederationController.php
  lib/Controller/OCSController.php
  lib/Controller/SettingsController.php
  lib/Controller/TemplatesController.php
  lib/Controller/WopiController.php
  lib/Db/AssetMapper.php
  lib/Db/DirectMapper.php
  lib/Db/Wopi.php
  lib/Db/WopiMapper.php
  lib/Events/BeforeFederationRedirectEvent.php
  lib/Exceptions/ExpiredTokenException.php
  lib/Exceptions/UnknownTokenException.php
  lib/Helper.php
  lib/Listener/FileCreatedFromTemplateListener.php
  lib/Middleware/WOPIMiddleware.php
  lib/Migration/Version2060Date20200302131958.php
  lib/Migration/Version2060Date20200302132145.php
  lib/Migration/Version30704Date20200626072306.php
  lib/Migration/Version30709Date20201111104147.php
  lib/Migration/Version30717Date20210310164901.php
  lib/PermissionManager.php
  lib/Preview/Office.php
  lib/Service/CapabilitiesService.php
  lib/Service/DemoService.php
  lib/Service/FederationService.php
  lib/Service/FontService.php
  lib/Service/UserScopeService.php
  lib/Settings/Admin.php
  lib/Template/CollaboraTemplateProvider.php
  lib/TemplateManager.php
  lib/TokenManager.php
  lib/WOPI/DiscoveryManager.php
  lib/WOPI/Parser.php
  psalm.xml
  tests/bootstrap.php
  tests/features/bootstrap/DirectContext.php
  tests/features/bootstrap/FederationContext.php
  tests/features/bootstrap/RichDocumentsContext.php
  tests/features/bootstrap/WopiContext.php
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: 3. to review

#2232 Backport translations to stable branches
  .tx/backport
Labels: bug, 3. to review
