Repository nextcloud/richdocuments, pull requests merged in 2022-11, with the labels that each got.

#2595 Improve error handling for global template uploads
  lib/Controller/TemplatesController.php
  templates/admin.php
Labels: bug, 3. to review

#2601 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2597 Adjust local editing button position in tabbed view
  src/document.js
Labels: 4. to release, design

#2600 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2615 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2616 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2626 Pass the proper target path/name for new files created through direct editing
  lib/Controller/DirectViewController.php
Labels: bug, 3. to review

#2640 Fix array access error when requesting preview while not having access to Collabora
  lib/Preview/Office.php
Labels: bug, 3. to review, backport-request

#2646 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2648 Add confirmation dialog after document is opened locally
  src/document.js
Labels: enhancement, 3. to review
