Repository nextcloud/richdocuments, pull requests merged in 2022-01, with the labels that each got.

#1945 Ensure that the guest name picker is shown on editable links
  src/document.js
  src/helpers/guestName.js
  src/view/Office.vue
Labels: bug, 3. to review, backport-request

#1883 Expose guest avatar images through wopi
  lib/Controller/WopiController.php
Labels: enhancement, 3. to review, backport-request

#1959 Don't wait DOMContentLoaded to register the viewer handler
  src/viewer.js
Labels: bug, 3. to review, javascript, regression
