Repository nextcloud/richdocuments, pull requests merged in 2022-07, with the labels that each got.

#2299 Updates "productName" in capabilities
  lib/Capabilities.php
Labels: 3. to review

#2274 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#2269 bugfix/noid/non visible create file
  src/files.js
Labels: bug, 3. to review

#2260 Fix encoding in filename
  src/view/Office.vue
Labels: bug, 3. to review

#2318 Fix incorrect HTML encoding of filename
  src/view/Office.vue
  templates/documents.php
Labels: bug, 3. to review

#2298 Fix: allow opening PDF with Collabora
  css/filetypes.scss
  src/viewer.js
Labels: enhancement, 3. to review
