Repository nextcloud/richdocuments, pull requests merged in 2022-03, with the labels that each got.

#2074 Prepare release of 4.2.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, release

#2075 Prepare release of 5.0.3
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3. to review, release

#2081 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#2086 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#2095 Fix: missing settings messages
  css/admin.scss
  css/templatePicker.scss
  src/components/AdminSettings.vue
Labels: bug, 3. to review
