Repository nextcloud/richdocuments, pull requests merged in 2023-10, with the labels that each got.

#3200 [stable27] fix: Mobile support shall be enabled by default
  lib/Capabilities.php
Labels: bug, 3. to review, regression

#3214 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3210 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3215 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3198 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3218 fix: Properly provide instance id
  lib/Service/InitialStateService.php
Labels: bug, 3. to review, high

#3231 [stable27] fix: Update file metadata only if file was changed
  src/view/FilesAppIntegration.js
  src/view/Office.vue
Labels: bug, 3. to review

#3230 fix: Update file metadata after save
  package-lock.json
  package.json
  src/view/FilesAppIntegration.js
  src/view/Office.vue
Labels: bug, 3. to review

#3206 Allow current user lock
  lib/Controller/WopiController.php
Labels: bug, 3. to review, backport-request

#3238 fix dropdowns have wrong mark color in browsers
  src/helpers/coolParameters.js
Labels: bug, 4. to release, backport-request

#3248 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3247 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3249 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3250 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3237 fix: Add proper feature policy
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/AppConfig.php
  lib/AppInfo/Application.php
  lib/Listener/AddContentSecurityPolicyListener.php
  lib/Listener/AddFeaturePolicyListener.php
  lib/Listener/CSPListener.php
  tests/OCA/Richdocuments/Listener/AddFeaturePolicyListenerTest.php
  tests/lib/AppConfigTest.php
  tests/lib/Listener/AddContentSecurityPolicyListenerTest.php
  tests/lib/Middleware/WOPIMiddlewareTest.php
  tests/lib/PermissionManagerTest.php
  tests/phpunit.xml
Labels: bug, 3. to review, backport-request, regression

#3253 chore(php): Add PHP 8.3 to test matrix
  .github/workflows/lint-php.yml
Labels: 3. to review

#3256 fix: Clear loading timeout when guest name is asked
  src/files.js
Labels: bug, backport-request

#3267 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3268 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
