Repository nextcloud/richdocuments, pull requests merged in 2023-01, with the labels that each got.

#2605 Another attempt to work around Safari issues
  src/document.js
  src/files.js
  src/helpers/safariFixer.js
  src/view/Office.vue
Labels: bug, 2. developing

#2713 fix(viewer): Do not attempt to register file actions if not available
  src/viewer.js
Labels: bug, 3. to review

#2723 fix: Open pdf files by default on share links if files_pdfviewer is disabled
  lib/Capabilities.php
Labels: bug, 3. to review

#1939 Add cypress tests
  .eslintrc.js
  .github/workflows/cypress.yml
  .gitignore
  cypress.config.ts
  cypress/e2e/new.spec.js
  cypress/e2e/open.spec.js
  cypress/e2e/settings.spec.js
  cypress/e2e/share-internal.spec.js
  cypress/fixtures/document.odt
  cypress/fixtures/drawing.odg
  cypress/fixtures/presentation.odp
  cypress/fixtures/spreadsheet.ods
  cypress/fixtures/test.md
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/e2e.js
  cypress/utils/index.js
  package-lock.json
  package.json
Labels: 2. developing

#2736 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2737 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2740 Fix creating new files from user templates
  cypress/e2e/new.spec.js
  cypress/e2e/share-internal.spec.js
  cypress/e2e/templates.spec.js
  cypress/fixtures/templates/presentation.otp
  cypress/support/commands.js
  lib/Middleware/WOPIMiddleware.php
Labels: bug, 3. to review

#2752 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2753 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2776 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2775 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
