Repository nextcloud/richdocuments, pull requests merged in 2023-11, with the labels that each got.

#3275 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3276 [stable27] Update files app state on saveAs
  package-lock.json
  package.json
  src/view/FilesAppIntegration.js
Labels: bug, 3. to review

#3277 fix: Properly update files app state when using saveAs
  src/view/FilesAppIntegration.js
Labels: bug, 3. to review

#3290 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3291 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3292 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3293 fix: Set proper user scope for direct editing
  lib/Controller/DirectViewController.php
Labels: bug, 3. to review, backport-request

#3298 fix: Set expect guzzle option to false
  lib/Preview/Office.php
Labels: bug, 3. to review

#3310 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3309 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3303 feat: add preview provider for emf files
  composer.json
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/AppInfo/Application.php
  lib/Preview/EMF.php
  tests/psalm-baseline.xml
Labels: enhancement, 3. to review, feature: previews and thumbnails

#3321 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3322 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
