Repository nextcloud/richdocuments, pull requests merged in 2023-09, with the labels that each got.

#3137 fix: Allow to opt-in loading image mimes on hide download shares
  lib/AppConfig.php
  lib/Capabilities.php
  src/files.js
Labels: bug, 3. to review

#3165 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3164 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3160 test(cypress): Add test for share token direct editing
  cypress/e2e/direct.spec.js
Labels: 3. to review, tests

#2301 Exclude MSOffice mime types association if OnlyOffice app is installed
  lib/Capabilities.php
  lib/Service/CapabilitiesService.php
Labels: enhancement, 4. to release

#3152 Version support and iframe refactoring
  .eslintrc.js
  appinfo/routes.php
  composer.lock
  cypress/e2e/integration.spec.js
  cypress/e2e/share-link.js
  cypress/fixtures/image.png
  cypress/support/commands.js
  cypress/support/e2e.js
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentController.php
  lib/Controller/DocumentTrait.php
  lib/Controller/SettingsController.php
  lib/Controller/WopiController.php
  lib/Db/Wopi.php
  lib/Service/InitialStateService.php
  lib/Service/UserScopeService.php
  lib/TemplateManager.php
  lib/TokenManager.php
  package-lock.json
  package.json
  src/document.js
  src/files.js
  src/helpers/coolParameters.js
  src/helpers/index.js
  src/mixins/openLocal.js
  src/mixins/pickLink.js
  src/mixins/saveAs.js
  src/mixins/uiMention.js
  src/mixins/version.js
  src/view/FilesAppIntegration.js
  src/view/Office.vue
  src/viewer.js
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: enhancement, 3. to review, backport-request

#3175 [stable27] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#3173 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3174 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3177 fix: Use userId as a fallback for new file creation token
  lib/Controller/DocumentController.php
Labels: bug, 3. to review

#3172 [stable27] Version support and iframe refactoring
  .eslintrc.js
  .github/workflows/integration.yml
  .github/workflows/phpunit-oci.yml
  appinfo/routes.php
  cypress/e2e/integration.spec.js
  cypress/e2e/share-link.js
  cypress/fixtures/image.png
  cypress/support/commands.js
  cypress/support/e2e.js
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentController.php
  lib/Controller/DocumentTrait.php
  lib/Controller/SettingsController.php
  lib/Controller/WopiController.php
  lib/Db/Wopi.php
  lib/Events/BeforeFederationRedirectEvent.php
  lib/Service/InitialStateService.php
  lib/Service/UserScopeService.php
  lib/TemplateManager.php
  lib/TokenManager.php
  src/document.js
  src/files.js
  src/helpers/coolParameters.js
  src/helpers/index.js
  src/mixins/openLocal.js
  src/mixins/pickLink.js
  src/mixins/saveAs.js
  src/mixins/uiMention.js
  src/mixins/version.js
  src/view/FilesAppIntegration.js
  src/view/Office.vue
  src/viewer.js
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: enhancement, 3. to review

#3171 [stable26] fix: Bring back version preview/restore
  src/document.js
  src/view/FilesAppIntegration.js
Labels: bug, 3. to review

#3183 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3184 fix: Mobile support shall be enabled by default
  lib/Capabilities.php
Labels: bug, 3. to review, backport-request, regression
