Repository nextcloud/richdocuments, pull requests merged in 2023-04, with the labels that each got.

#2889 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2890 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2880 fix: Properly select save as dialog buttons
  src/document.js
Labels: backport-request

#2893 fix: Avoid error when browser cannot detect font mimetype
  lib/Controller/SettingsController.php
  src/components/AdminSettings.vue
Labels: bug, 3. to review

#2860 Add modal to set zotero API key during editing
  lib/Controller/WopiController.php
  package-lock.json
  package.json
  src/components/Modal/ZoteroHint.vue
  src/services/api.js
  src/view/Office.vue
Labels: enhancement, 3. to review

#2881 fix(files): Avoid reloading the file list and use update methods instead
  src/view/FilesAppIntegration.js
  src/view/Office.vue
Labels: bug, 3. to review, backport-request

#2899 fix: Avoid setting user scope for share links
  lib/Controller/WopiController.php
Labels: bug, 3. to review

#2919 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
