Repository nextcloud/richdocuments, pull requests merged in 2023-02, with the labels that each got.

#2782 allow to add ttf files
  lib/Controller/SettingsController.php
  src/components/AdminSettings.vue
Labels: 3. to review, backport-request

#2787 [stable24] Fix loading share links for logged in users
  lib/PermissionManager.php
  tests/psalm-baseline.xml
Labels: bug, 3. to review

#2786 [stable25] Fix loading share links for logged in users
  lib/PermissionManager.php
  tests/psalm-baseline.xml
Labels: bug, 3. to review

#2258 Move document params to initial state
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentController.php
  lib/Controller/DocumentTrait.php
  lib/Service/InitialStateService.php
  src/services/config.tsx
  templates/documents.php
  tests/features/bootstrap/DirectContext.php
  tests/features/bootstrap/RichDocumentsContext.php
  tsconfig.json
Labels: 3. to review, technical debt

#2802 release: Bump version to 6.3.4
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3. to review, release

#2801 Fix viewer height on safari mobile
  src/view/Office.vue
Labels: bug, 3. to review, design, client: 🤖🍏 mobile

#2815 ci: Pin phpunit version
  .github/workflows/phpunit.yml
Labels: backport-request

#2811 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2810 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2807 [stable24] Fix viewer height on safari mobile
  src/view/Office.vue
Labels: bug, 3. to review, design, client: 🤖🍏 mobile
