Repository nextcloud/richdocuments, pull requests merged in 2023-07, with the labels that each got.

#3055 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3056 [stable26] Update nextcloud/ocp dependency
  composer.lock
  composer/composer/ClassLoader.php
Labels: 3. to review, dependencies

#3059 fix: Create empty files from template if available
  lib/Listener/FileCreatedFromTemplateListener.php
Labels: bug, 3. to review, backport-request

#3058 Fix document target picker and add slide support
  lib/Service/FileTargetService.php
  src/document.js
  src/view/DocumentTargetPicker.vue
  src/view/Office.vue
Labels: bug, 3. to review, backport-request

#3073 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3074 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3042 fix(Wopi): Mark sensitive parameter as such
  lib/AppInfo/Application.php
  lib/Db/WopiMapper.php
  tests/stub.phpstub
Labels: bug, 3. to review

#3030 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#3083 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
