Repository nextcloud/richdocuments, pull requests merged in 2023-06, with the labels that each got.

#2978 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#2977 ci: Switch to ghcr.io images
  .github/workflows/cypress.yml
  .github/workflows/integration.yml
  cypress/e2e/open.spec.js
  tests/lib/PermissionManagerTest.php
Labels: 3. to review, tests

#2976 fix(event): Replace deprecated 3rdparty event with our OCP event
  lib/Events/BeforeFederationRedirectEvent.php
Labels: bug, 3. to review

#2982 chore(CSP): Remove deprecated inline js CSP
  lib/Controller/DocumentTrait.php
Labels: 3. to review, technical debt

#2975 Document targets
  appinfo/routes.php
  composer.json
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/AppConfig.php
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Controller/DocumentController.php
  lib/Controller/TargetController.php
  lib/Listener/ReferenceListener.php
  lib/Reference/OfficeTargetReferenceProvider.php
  lib/Service/FileTargetService.php
  lib/Service/RemoteService.php
  src/document.js
  src/helpers/url.js
  src/reference.js
  src/view/DocumentTargetPicker.vue
  src/view/Office.vue
  webpack.js
Labels: enhancement, 3. to review

#2997 fix: Allow dynamic autoloading for classes added during upgrade
  composer/composer.json
  composer/composer/autoload_real.php
Labels: backport-request

#3010 fix: Catch and skip errors for adjusting the files view when the file is not present in the list
  src/view/FilesAppIntegration.js
Labels: bug, 3. to review

#3022 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3023 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2948 Use the color-primary-element* variables
  css/files.scss
  src/helpers/coolParameters.js
Labels: bug, 3. to review, design

#3031 Accept alternative MIME type for OpenType fonts
  lib/Controller/SettingsController.php
Labels: bug, 3. to review, backport-request
