Repository nextcloud/richdocuments, pull requests merged in 2023-03, with the labels that each got.

#2814 Integrate the link picker
  lib/Controller/DocumentTrait.php
  lib/Controller/WopiController.php
  package-lock.json
  package.json
  src/document.js
Labels: enhancement, 3. to review, integration

#2826 Fix base64 image generation
  src/document.js
Labels: bug, 3. to review

#2840 [stable26] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#2846 fix: Trigger initial setup earlier
  src/files.js
Labels: backport-request

#2845 fix(auto_logout): Register auto_logout listeners to prevent auto_logout while editing
  src/document.js
Labels: backport-request

#2856 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2872 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2871 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2870 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2831 fix: Avoid error when federation is disabled
  lib/AppInfo/Application.php
  lib/Settings/Personal.php
Labels: bug, 3. to review

#2876 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
