Repository nextcloud/richdocuments, pull requests merged in 2023-05, with the labels that each got.

#2940 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2939 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2944 Improve group multiselect behaviour with multiple and long group names
  src/components/AdminSettings.vue
  src/components/SettingsSelectGroup.vue
Labels: bug, 3. to review, backport-request

#2953 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2957 [stable26] Bump version to 8.0.2
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: release

#2955 Bump version to 8.1.0-beta.1
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: release

#2956 [stable25] Bump version to 7.1.4
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: release

#2962 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2964 fix: Pass over dark/light variants of our css variables
  lib/Service/InitialStateService.php
  src/helpers/coolParameters.js
  templates/documents.php
Labels: bug, 3. to review

#2972 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
