Repository nextcloud/richdocuments, pull requests merged in 2023-12, with the labels that each got.

#3330 fix: Fix version access with new version backend on shared files
  lib/Controller/WopiController.php
Labels: bug, 3. to review

#3341 Fix opening file after rename in COOL
  src/view/FilesAppIntegration.js
Labels: bug, 3. to review

#3345 fix: Make rename update the file list properly on files2vue
  src/view/FilesAppIntegration.js
  src/view/Office.vue
Labels: bug, 3. to review, backport-request

#3304 Feature/fonts improvement
  .gitignore
  .nextcloudignore
  appinfo/info.xml
  assets/fonts/.gitkeep
  assets/fonts/AmaticSC-Regular.LICENSE.txt
  assets/fonts/AmaticSC-Regular.ttf
  build/download-fonts.sh
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  cypress/e2e/settings.spec.js
  krankerl.toml
  lib/Command/InstallDefaultFonts.php
  lib/Migration/InstallDefaultFonts.php
  lib/Service/FontService.php
  src/components/AdminSettings.vue
  tests/psalm-baseline.xml
Labels: enhancement, 3. to review, feature: fonts

#3352 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3353 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3354 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3361 fix: Use proper blob url for all fonts
  build/download-fonts.sh
Labels: bug, 3. to review, backport-request

#3364 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3356 fix: mention popup reappears after inserting the mention
  src/view/Office.vue
Labels: bug, 3. to review, backport-request

#3369 fix: Avoid 3px offset on public share links
  css/files.scss
Labels: bug, 3. to review, backport-request

#3372 fix: Consider owner group membership for public share links
  lib/TokenManager.php
Labels: bug, 3. to review

#3378 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3379 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3380 fix(Application.php): Update methods post-refactor
  lib/AppInfo/Application.php
Labels: bug, 3. to review

#3382 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#3381 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#2945 Switch to NcSelect and `@nextcloud/vue` 8
  .eslintrc.js
  cypress/e2e/integration.spec.js
  package-lock.json
  package.json
  src/admin.js
  src/components/AdminSettings.vue
  src/components/Modal/Confirmation.vue
  src/components/Modal/SaveAs.vue
  src/components/SettingsSelectGroup.vue
  src/components/SettingsSelectTag.vue
  src/document.js
  src/files.js
  src/helpers/types.js
  src/helpers/url.js
  src/init-shared.js
  src/mixins/openLocal.js
  src/mixins/saveAs.js
  src/personal.js
  src/reference.js
  src/view/DocumentTargetPicker.vue
  src/view/FilesAppIntegration.js
  src/view/NewFileMenu.js
  src/view/Office.vue
  src/viewer.js
Labels: 3. to review, technical debt

#3311 feat: add loadingMessage() to show different loadingMsg
  src/view/Office.vue
Labels: bug, 3. to review

#3384 enh(Issue_Template) Request richdocuments config in bug reports
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: enhancement, 3. to review
