Repository nextcloud/richdocuments, pull requests merged in 2024-11, with the labels that each got.

#4125 Move template settings to vue component
  css/admin.scss
  cypress/e2e/settings.spec.js
  cypress/e2e/templates.spec.js
  cypress/support/commands.js
  lib/Service/InitialStateService.php
  lib/Settings/Admin.php
  src/admin.js
  src/components/AdminSettings.vue
  src/components/AdminSettings/GlobalTemplates.vue
  templates/admin.php
Labels: enhancement, technical debt, php, javascript, tests

#4190 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4192 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4191 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4193 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4171 fix: get user by display name
  lib/Controller/MentionController.php
Labels: bug, 3. to review, backport-request, php

#4219 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4218 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4178 skip css variable if not set (prevent warning on COOL side)
  src/helpers/coolParameters.js
Labels: backport-request, feedback-requested

#4217 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4230 fix: use new db types constants
  lib/Db/Asset.php
  lib/Db/Direct.php
  lib/Db/Wopi.php
Labels: 3. to review

#4226 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4231 fix: Limit open with Collabora action to pdf files
  src/file-actions.js
Labels: bug, 3. to review, backport-request

#4240 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4209 feat: `startPresentation` URL parameter
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Service/InitialStateService.php
  src/helpers/url.js
  src/view/Office.vue
Labels: enhancement, 2. developing

#4249 Implement support for insertion of multimedia from Nextcloud assets
  docs/frontend-integration.md
  lib/Controller/WopiController.php
  src/view/FilesAppIntegration.js
  src/view/Office.vue
Labels: enhancement, 3. to review

#4266 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4253 Fix errors when extracting content controls
  lib/Service/TemplateFieldService.php
Labels: bug, 3. to review, backport-request

#4269 fix: remove deprecated `title` parameter
  src/helpers/url.js
  src/view/FilesAppIntegration.js
  src/view/Office.vue
Labels: 3. to review, backport-request

#4195 fix(share): link share of federated share
  cypress/e2e/share-federated.spec.js
  cypress/support/commands.js
  lib/Controller/DocumentController.php
Labels: bug, 4. to release, feature: federation, regression

#4265 [stable30] Fix npm audit
  package-lock.json
  package.json
  src/components/Modal/SaveAs.vue
  src/components/Modal/ZoteroHint.vue
  src/viewer.js
Labels: 3. to review, dependencies

#4264 [stable29] Fix npm audit
  package-lock.json
  package.json
  src/components/Modal/SaveAs.vue
  src/components/Modal/ZoteroHint.vue
  src/viewer.js
Labels: 3. to review, dependencies

#4285 ci: Attempt to make cypress tests more stable with a unified wait for close
  .github/workflows/cypress-e2e.yml
  cypress/e2e/integration.spec.js
  cypress/e2e/new.spec.js
  cypress/e2e/share-federated.spec.js
  cypress/e2e/share-internal.spec.js
  cypress/e2e/share-link.js
  cypress/support/commands.js
Labels: 3. to review, backport-request, tests

#4278 fix: Apply viewer wrapper as we do it in text
  src/components/Modal/ZoteroHint.vue
  src/view/Office.vue
  src/view/Viewer.vue
  src/viewer.js
Labels: bug, 3. to review, backport-request
