Repository nextcloud/richdocuments, pull requests merged in 2024-10, with the labels that each got.

#4097 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4100 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4047 chore: Move to attributes in WopiController
  appinfo/routes.php
  lib/Controller/WopiController.php
Labels: 3. to review, technical debt

#4104 fix: display proper custom logo in collabora
  lib/Service/InitialStateService.php
  src/helpers/coolParameters.js
  tests/stub.phpstub
Labels: bug, backport-request, php, javascript

#4119 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4118 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4124 Fix: Fix Admin Settings page when Watermark label selected
  lib/AppConfig.php
Labels: 2. developing, backport-request

#4121 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4120 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4098 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4099 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4131 [stable24] Update empty templates
  emptyTemplates/document.ott
  emptyTemplates/template.odt
Labels: bug, 3. to review

#4132 Fix asset download checks
  lib/Controller/AssetsController.php
  src/view/FilesAppIntegration.js
Labels: bug, 3. to review

#4134 [stable29] Fix asset download checks
  lib/Controller/AssetsController.php
  src/view/FilesAppIntegration.js
Labels: bug, 3. to review

#4133 [stable30] Fix asset download checks
  lib/Controller/AssetsController.php
  src/view/FilesAppIntegration.js
Labels: bug, 3. to review

#4135 [stable28] Fix asset download checks
  lib/Controller/AssetsController.php
Labels: bug, 3. to review

#4136 [stable27] Fix asset download checks
  lib/Controller/AssetsController.php
Labels: bug, 3. to review

#4141 [stable30] Add brute force protection for public file creation
  lib/Controller/DocumentAPIController.php
Labels: bug, 3. to review

#4142 [stable29] Add brute force protection for public file creation
  lib/Controller/DocumentAPIController.php
Labels: bug, 3. to review

#4143 [stable28] Add brute force protection for public file creation
  lib/Controller/DocumentAPIController.php
Labels: bug, 3. to review

#4140 Add brute force protection for public file creation
  lib/Controller/DocumentAPIController.php
Labels: bug, 3. to review

#4144 [stable27] Add brute force protection for public file creation
  lib/Controller/DocumentAPIController.php
Labels: bug, 3. to review

#4137 [stable26] Fix asset download checks
  lib/Controller/AssetsController.php
Labels: bug, 3. to review

#4138 [stable25] Fix asset download checks
  lib/Controller/AssetsController.php
Labels: bug, 3. to review

#4145 [stable26] Add brute force protection for public file creation
  lib/Controller/DocumentAPIController.php
Labels: bug, 3. to review

#4147 [stable25] Add brute force protection for public file creation
  lib/Controller/DocumentAPIController.php
Labels: bug, 3. to review

#4154 Release/v7.1.10
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: release

#4153 Release/v8.0.11
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: release

#4152 Release/v8.2.14
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: release

#4151 Release/v8.3.12
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: release

#4150 Release/v8.4.8
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: release

#4149 Release/v8.5.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: release

#4155 fix(github): adjust workflows docker images
  .github/workflows/integration.yml
Labels: 3. to review, backport-request

#4129 Digitally sign documents via software certificates
  css/admin.scss
  lib/Controller/SettingsController.php
  lib/Controller/WopiController.php
  lib/Service/CapabilitiesService.php
  lib/Settings/Personal.php
  src/personal.js
  templates/personal.php
Labels: enhancement, 3. to review

#4161 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4164 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4162 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4163 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4182 Release/v6.3.11
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, release
