Repository nextcloud/richdocuments, pull requests merged in 2024-05, with the labels that each got.

#3645 File action to open PDFs with richdocuments when files_pdfviewer is enabled
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  img/app.svg
  lib/AppInfo/Application.php
  lib/Listener/LoadAdditionalListener.php
  src/file-actions.js
  webpack.js
Labels: bug, 3. to review, regression

#3648 Fix chunk loading error
  src/components/GuestNamePicker.vue
  src/files.js
  src/init-shared.js
  src/personal.js
  src/public.js
  src/reference.js
  src/viewer.js
  webpack.js
Labels: bug, 3. to review

#3651 chore: Release 8.2.9
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, release

#3663 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3654 test(open-pdf): open pdf with richdocuments via file-action
  .github/workflows/cypress.yml
  cypress/e2e/open.spec.js
  cypress/fixtures/document.pdf
  cypress/support/commands.js
Labels: bug, 3. to review, regression

#3672 fix: Avoid loading file actions if app is disabled for users
  lib/Listener/LoadAdditionalListener.php
Labels: bug, 3. to review

#3681 Test guest name setting
  lib/Controller/DocumentController.php
  lib/TokenManager.php
  tests/composer.lock
  tests/features/bootstrap/RichDocumentsContext.php
  tests/features/bootstrap/WopiContext.php
  tests/features/wopi.feature
Labels: bug, 3. to review, backport-request, tests

#3685 fix: Avoid triggering file list requests during handover to desktop client
  src/mixins/openLocal.js
  src/view/Office.vue
Labels: bug, 3. to review, backport-request

#3697 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3698 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3696 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3695 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3707 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3715 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
