Repository nextcloud/richdocuments, pull requests merged in 2024-04, with the labels that each got.

#3576 ci: Adadpt min php version to 8.1
  .github/workflows/cypress.yml
  .github/workflows/integration.yml
  .github/workflows/lint-php.yml
Labels: 3. to review, tests

#3575 [stable27] fix: Allow configuring the wopi_callback_url
  lib/Service/InitialStateService.php
  src/helpers/url.js
Labels: bug, 3. to review

#3569 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3580 fix: Use wopi callback url for all urls handed over to Collabora
  lib/Controller/WopiController.php
  src/helpers/url.js
Labels: bug, 3. to review

#3596 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3595 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3570 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3571 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3582 chore: Cleanup old TemplateSaveAs code as this is no longer supported by Collabora
  lib/Capabilities.php
  lib/Controller/DirectViewController.php
  lib/Controller/WopiController.php
  lib/Db/Wopi.php
  lib/Db/WopiMapper.php
  lib/Service/CapabilitiesService.php
  lib/Settings/Admin.php
  lib/Settings/Personal.php
  lib/TokenManager.php
Labels: 3. to review, technical debt

#3601 fix: Use Close_Session post message to properly end the Collabora editing before opening locally
  cypress/e2e/integration.spec.js
  lib/Controller/WopiController.php
  src/mixins/openLocal.js
  src/view/Office.vue
Labels: bug, 3. to review, backport-request

#3597 [stable26] fix: Use Close_Session post message to properly end the Collabora editing before opening locally
  lib/Controller/WopiController.php
  src/document.js
  src/view/Office.vue
Labels: bug, backport-request

#3600 refactor: move to office.vue component
  cypress/e2e/share-link.js
  lib/Listener/ShareLinkListener.php
  src/files.js
  src/helpers/isDocument.js
  src/helpers/isPublicPage.js
  src/public.js
  src/view/Office.vue
  webpack.js
Labels: enhancement, 2. developing, technical debt

#3633 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3614 perf(bootstrap): Lazy register template creator through event
  composer.lock
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/AppInfo/Application.php
  lib/Listener/RegisterTemplateFileCreatorListener.php
Labels: 3. to review, performance 🚀

#3634 test(cypress): Adapt selectors to Collabora 24.04
  cypress/e2e/integration.spec.js
  cypress/e2e/open.spec.js
  cypress/e2e/share-link.js
  cypress/support/commands.js
  src/view/Office.vue
Labels: 3. to review, tests

#3624 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies
