Repository nextcloud/richdocuments, pull requests merged in 2024-01, with the labels that each got.

#3224 fix: Disable auto logout while editing
  appinfo/routes.php
  lib/Controller/DocumentController.php
  src/mixins/autoLogout.js
  src/view/Office.vue
Labels: bug, 3. to review, backport-request

#3391 fix(i18n): Improved grammar
  src/mixins/saveAs.js
Labels: backport-request

#3393 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3394 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3395 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3397 [stable26] fix: Set proper user scope for direct editing
  lib/Controller/DirectViewController.php
Labels: bug, 3. to review

#3399 [stable27] feat: add loadingMessage() to show different loadingMsg
  src/view/Office.vue
Labels: bug, 3. to review

#3398 [stable27] fix: mention popup reappears after inserting the mention
  src/view/Office.vue
Labels: bug, 4. to release

#3400 [stable28] feat: add loadingMessage() to show different loadingMsg
  src/view/Office.vue
Labels: bug, 3. to review

#3403 fix: Let wopi middleware also handle asset fetching
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/Controller/AssetsController.php
  lib/Controller/Attribute/RestrictToWopiServer.php
  lib/Controller/WopiController.php
  lib/Middleware/WOPIMiddleware.php
Labels: bug, 3. to review, technical debt

#3410 test(ci): use only 3 runners for cypress
  .github/workflows/cypress.yml
Labels: enhancement, 3. to review, backport-request, tests

#3413 test(ci): use only 3 runners for cypress
  .github/workflows/cypress.yml
Labels: 3. to review, technical debt, performance 🚀, tests

#3411 test(ci): use only 3 runners for cypress
  .github/workflows/cypress.yml
Labels: 3. to review, technical debt, tests

#3419 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3418 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3432 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3424 ActivateConfig: add type declarations
  lib/Command/ActivateConfig.php
Labels: 3. to review, technical debt

#3442 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
