Repository nextcloud/richdocuments, pull requests merged in 2024-03, with the labels that each got.

#3510 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3513 fix: Avoid absolute positioning on interactive widgets
  src/view/Office.vue
Labels: bug, 3. to review

#3521 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3522 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3524 fix: Use new viewer api to open files again after open locally
  src/mixins/openLocal.js
Labels: bug, 3. to review, backport-request

#3535 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3541 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3538 feat: Add new mdi icons
  img/x-office-document.svg
  img/x-office-drawing.svg
  img/x-office-presentation.svg
  img/x-office-spreadsheet.svg
  lib/AppInfo/Application.php
Labels: enhancement, 3. to review

#3528 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#3515 Fix open locally with files lock and wopi allow list (backport stable26)
  appinfo/routes.php
  lib/Controller/DocumentAPIController.php
  lib/Service/InitialStateService.php
  src/document.js
Labels: bug, 3. to review

#3539 match dark theme of system if no nextcloud theme specified
  src/helpers/coolParameters.js
Labels: bug, 2. developing, backport-request

#3556 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
