Repository nextcloud/richdocuments, pull requests merged in 2024-12, with the labels that each got.

#4298 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4299 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4296 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4102 fix: Add proper messages to mention response
  lib/Controller/MentionController.php
Labels: enhancement, 3. to review

#4028 [stable30] fix: use file picker component directly
  cypress/e2e/integration.spec.js
  cypress/fixtures/document.odt
  cypress/support/commands.js
  lib/Listener/LoadViewerListener.php
  src/view/DocumentTargetPicker.vue
Labels: 3. to review

#4306 fix: do not treat guest as share owner
  lib/Controller/DocumentController.php
  lib/Controller/WopiController.php
  lib/TokenManager.php
  tests/features/bootstrap/WopiContext.php
  tests/features/wopi.feature
Labels: bug, 3. to review, backport-request, php

#4101 fix: Use proper file id for direct editing
  cypress/e2e/direct.spec.js
  lib/Controller/DirectViewController.php
  lib/Controller/OCSController.php
  lib/Db/DirectMapper.php
Labels: bug, 3. to review, backport-request, regression

#4210 feat: use autocomplete api for mentions
  lib/Controller/MentionController.php
  src/mixins/uiMention.js
Labels: enhancement, 4. to release

#4334 chore: Update php requirement for composer
  .github/workflows/update-nextcloud-ocp.yml
  composer.json
Labels: 3. to review, technical debt

#4346 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4333 feat: insert text and images generated with nextcloud assistant
  appinfo/routes.php
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/Controller/AssetsController.php
  lib/Controller/WopiController.php
  lib/TaskProcessingManager.php
  src/mixins/assistant.js
  src/view/Office.vue
Labels: enhancement, 2. developing, javascript, integration

#4335 fix: Properly get empty template for direct editing
  cypress/e2e/direct.spec.js
  lib/Controller/DirectViewController.php
Labels: bug, 3. to review

#4328 feat: electronic signing, add settings for eIDEasy
  docs/app_settings.md
  lib/Controller/SettingsController.php
  lib/Controller/WopiController.php
  lib/Settings/Admin.php
  src/components/AdminSettings.vue
Labels: enhancement, 3. to review

#4356 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4360 Skip errors that may interrupt file creation
  lib/Listener/FileCreatedFromTemplateListener.php
  lib/Service/RemoteOptionsService.php
  tests/composer.lock
Labels: bug, 3. to review

#4355 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4350 Add Template and pages/numbers/keynote mimetypes
  lib/Capabilities.php
Labels: enhancement, 3. to review

#4358 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4359 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
