Repository nextcloud/richdocuments, pull requests merged in 2024-09, with the labels that each got.

#3967 fix: Catch parsing errors or null doc structure
  lib/Service/TemplateFieldService.php
Labels: bug, 3. to review

#3969 fix: Dispatch event instead of hook for audit logging
  lib/TokenManager.php
  tests/psalm-baseline.xml
Labels: bug, 3. to review, backport-request

#3966 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3965 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3974 chore: upgrade `@nextcloud/files` to 3.8.0
  package-lock.json
  package.json
Labels: bug, 3. to review, high, dependencies

#3973 chore: monitor stable branches npm upgrades
  .github/dependabot.yml
Labels: 3. to review

#3993 [stable28] fix(client): Use shared default options for HTTP client requests
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/Preview/Office.php
  lib/Service/RemoteOptionsService.php
  lib/Service/RemoteService.php
Labels: bug, 3. to review

#4006 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3992 fix: pressing `Enter` submits guest name input
  src/components/GuestNamePicker.vue
Labels: 3. to review, design, javascript

#4005 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4008 [stable28] fix: pressing `Enter` submits guest name input
  src/components/GuestNamePicker.vue
Labels: 3. to review

#4009 [stable30] fix: pressing `Enter` submits guest name input
  src/components/GuestNamePicker.vue
Labels: 3. to review

#4007 [stable29] fix: pressing `Enter` submits guest name input
  src/components/GuestNamePicker.vue
Labels: 3. to review

#4004 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4013 [stable28] chore(deps): update @nextcloud dependencies
  .github/workflows/cypress.yml
  package-lock.json
  package.json
Labels: bug, 3. to review, dependencies

#4022 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4021 [stable30] Fix npm audit
  .github/workflows/cypress-e2e.yml
  package-lock.json
Labels: 3. to review, dependencies

#4020 [main] Fix npm audit
  .github/workflows/cypress-e2e.yml
  package-lock.json
Labels: 3. to review, dependencies

#3951 feat: Add parameter to allow converting files after filling out fields
  .github/workflows/integration.yml
  REUSE.toml
  lib/Controller/TemplateFieldController.php
  lib/Preview/Office.php
  lib/Service/RemoteService.php
  lib/Service/TemplateFieldService.php
  tests/config/behat.yml
  tests/data/form.odt
  tests/features/api.feature
  tests/features/bootstrap/ApiContext.php
Labels: bug, 4. to release

#4030 fix: failed token generation on public shares
  package-lock.json
  package.json
  src/helpers/url.js
  src/services/api.js
  src/view/Office.vue
Labels: bug, 3. to review, dependencies, javascript

#4043 feat(sharing): use `@nextcloud/sharing` to detect is public share
  src/helpers/index.js
  src/helpers/isPublicPage.js
  src/public.js
  src/view/FilesAppIntegration.js
  src/view/Office.vue
Labels: 3. to review

#4038 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4039 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4045 Add rector
  composer.json
  composer.lock
  lib/AppConfig.php
  lib/Backgroundjobs/Cleanup.php
  lib/Capabilities.php
  lib/Command/ConvertToBigInt.php
  lib/Command/InstallDefaultFonts.php
  lib/Command/UpdateEmptyTemplates.php
  lib/Controller/AssetsController.php
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentAPIController.php
  lib/Controller/DocumentController.php
  lib/Controller/DocumentTrait.php
  lib/Controller/FederationController.php
  lib/Controller/OCSController.php
  lib/Controller/SettingsController.php
  lib/Controller/TargetController.php
  lib/Controller/TemplateFieldController.php
  lib/Controller/TemplatesController.php
  lib/Controller/WopiController.php
  lib/Db/AssetMapper.php
  lib/Db/DirectMapper.php
  lib/Db/Wopi.php
  lib/Db/WopiMapper.php
  lib/Events/BeforeFederationRedirectEvent.php
  lib/Events/DocumentOpenedEvent.php
  lib/Helper.php
  lib/Listener/BeforeFetchPreviewListener.php
  lib/Listener/BeforeGetTemplatesListener.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Listener/LoadViewerListener.php
  lib/Listener/ShareLinkListener.php
  lib/Middleware/WOPIMiddleware.php
  lib/Migration/InstallDefaultFonts.php
  lib/PermissionManager.php
  lib/Service/CachedRequestService.php
  lib/Service/DemoService.php
  lib/Service/FederationService.php
  lib/Service/FontService.php
  lib/Service/PdfService.php
  lib/Service/RemoteService.php
  lib/Service/UserScopeService.php
  lib/Settings/Admin.php
  lib/Settings/Personal.php
  lib/Settings/Section.php
  lib/Template/CollaboraTemplateProvider.php
  lib/TemplateManager.php
  lib/WOPI/Parser.php
  rector.php
  tests/OCA/Richdocuments/Listener/AddFeaturePolicyListenerTest.php
  tests/bootstrap.php
  tests/features/bootstrap/ApiContext.php
  tests/features/bootstrap/DirectContext.php
  tests/features/bootstrap/RichDocumentsContext.php
  tests/lib/Listener/AddContentSecurityPolicyListenerTest.php
Labels: 3. to review, technical debt

#4014 Change some element selectors to fix a few Cypress tests
  cypress/e2e/share-link.js
  cypress/e2e/templates.spec.js
Labels: 2. developing, tests

#4063 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4065 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4066 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4048 fix(sharing): Don't ask for guest name on view-only share
  cypress/e2e/share-link.js
  src/helpers/guestName.js
Labels: bug, 3. to review, backport-request

#4064 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4062 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4050 fix: Properly render compare view
  src/view/Office.vue
  src/viewer.js
Labels: bug, 3. to review, backport-request

#3960 fix: Emit notification on mentions
  appinfo/routes.php
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/AppInfo/Application.php
  lib/Controller/MentionController.php
  lib/Notification/Notifier.php
  src/mixins/uiMention.js
  src/view/Office.vue
Labels: enhancement, 3. to review, backport-request

#4091 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4093 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4092 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4090 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
