Repository nextcloud/richdocuments, pull requests merged in 2024-02, with the labels that each got.

#3422 Update npm and node engines versions
  package.json
Labels: dependencies

#3457 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3469 fix: Drop use of deprecated jquery load
  src/document.js
Labels: bug, 3. to review

#3479 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3475 fix: emit allow attribute on iframe for the clipboard (fixes #3474)
  src/view/Office.vue
Labels: bug, 3. to review

#3464 perf: Change to individual dist imports to decrease loaded component impact
  src/components/Modal/Confirmation.vue
  src/components/Modal/SaveAs.vue
  src/components/Modal/ZoteroHint.vue
  src/view/DocumentTargetPicker.vue
  src/view/Office.vue
Labels: 3. to review, performance

#3491 Fix preview URLs and migrate providers to new API
  lib/AppConfig.php
  lib/AppInfo/Application.php
  lib/Preview/EMF.php
  lib/Preview/MSExcel.php
  lib/Preview/MSWord.php
  lib/Preview/OOXML.php
  lib/Preview/Office.php
  lib/Preview/OpenDocument.php
  lib/Preview/Pdf.php
  tests/psalm-baseline.xml
Labels: bug, 3. to review, technical debt

#3490 fix: Properly use input model in settings text fields
  src/components/SettingsInputText.vue
Labels: bug, 3. to review

#3501 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3489 Fix open locally with files lock and wopi allow list
  appinfo/routes.php
  lib/Controller/DocumentAPIController.php
  lib/Service/InitialStateService.php
  src/mixins/openLocal.js
  src/view/Office.vue
Labels: bug, 3. to review, backport-request
