Repository nextcloud/richdocuments, pull requests merged in 2024-07, with the labels that each got.

#3803 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3812 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3814 Migrate REUSE to TOML format
  .github/workflows/reuse.yml
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt

#3818 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3820 perf: Use getFirstNodeById as it is cached
  REUSE.toml
  lib/Controller/AssetsController.php
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentAPIController.php
  lib/Controller/DocumentController.php
  lib/Controller/OCSController.php
  lib/Controller/WopiController.php
  lib/Reference/OfficeTargetReferenceProvider.php
  lib/TemplateManager.php
  lib/TokenManager.php
  tests/psalm-baseline.xml
Labels: 3. to review, performance 🚀

#3819 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3763 richdocuments: add host_session_id parameter
  src/document.js
  src/view/Office.vue
Labels: enhancement, 2. developing, feedback-requested

#3829 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3828 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3817 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3831 fix(client): Use shared default options for HTTP client requests
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/Preview/Office.php
  lib/Service/CachedRequestService.php
  lib/Service/RemoteOptionsService.php
  lib/Service/RemoteService.php
Labels: bug, 3. to review, backport-request

#3798 feat: PDF Template Workflow
  appinfo/routes.php
  composer.lock
  composer/composer/autoload_classmap.php
  composer/composer/autoload_static.php
  lib/AppInfo/Application.php
  lib/Controller/TemplateFieldController.php
  lib/Listener/BeforeGetTemplatesListener.php
  lib/Listener/FileCreatedFromTemplateListener.php
  lib/Service/TemplateFieldService.php
  lib/Template/CollaboraTemplateProvider.php
Labels: enhancement, 2. developing, php, feature: templates

#3836 Prepare for 8.5.0-beta.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: enhancement, 3. to review, release

#3848 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3847 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3849 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3846 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3840 fix: Allow passing css var to change Collabora logo color
  src/helpers/coolParameters.js
Labels: 2. developing, javascript

#3853 [stable29] Allow passing css var to change Collabora logo color
  src/helpers/coolParameters.js
Labels: 3. to review, backport-request

#3854 [stable28] Allow passing css var to change Collabora logo color
  src/helpers/coolParameters.js
Labels: 3. to review, backport-request

#3855 [stable27] Allow passing css var to change Collabora logo color
  src/helpers/coolParameters.js
Labels: 3. to review, backport-request

#3833 chore: Switch to new API to set volatile user to prevent persisting it in any case
  lib/Service/UserScopeService.php
Labels: bug, 3. to review
