Repository nextcloud/richdocuments, pull requests merged in 2024-08, with the labels that each got.

#3863 Prepare for release 8.2.12
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3864 Prepare for release 8.3.9
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3866 Prepare for release 8.4.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3869 ci: Run cypress against code nightly
  .github/workflows/cypress-e2e.yml
  .github/workflows/integration.yml
  cypress/support/commands.js
Labels: 3. to review, tests

#3870 chore: Remove unnecessary files from release build
  .nextcloudignore
  .scrutinizer.yml
Labels: bug, 3. to review, backport-request

#3876 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3872 fix: Show PDF even when download hidden on public share
  lib/Listener/ShareLinkListener.php
  src/files.js
  src/helpers/index.js
  src/helpers/isDownloadHidden.js
  src/helpers/isPdf.js
  src/public.js
  webpack.js
Labels: bug, 2. developing, backport-request, javascript, regression

#3890 ci: Properly split with multi-collabora matrix
  .github/workflows/cypress-e2e.yml
  cypress/e2e/integration.spec.js
Labels: bug, 3. to review, tests

#3832 fix: Do not ask for guest name on read only pdfs
  src/helpers/guestName.js
  src/view/Office.vue
Labels: bug, 3. to review

#3885 feat(tests): Implement testing for new template workflow (filling templates)
  cypress/e2e/templates.spec.js
  cypress/fixtures/templates/document_template_with_fields.odt
  cypress/support/commands.js
  lib/Service/TemplateFieldService.php
Labels: enhancement, 2. developing, javascript, tests, feature: templates

#3924 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3923 [stable30] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#3914 Fixes #3902 : allow double click in image picker
  src/view/FilesAppIntegration.js
Labels: backport-request

#3925 fix(branding): properly send custom logo to collabora
  src/helpers/coolParameters.js
Labels: bug, 3. to review, backport-request, javascript, branding, regression

#3916 Cache `extractFields` response from Collabora
  lib/Service/TemplateFieldService.php
Labels: 3. to review, php, performance 🚀, feature: templates

#3930 [stable28] fix(branding): properly send custom logo to collabora
  src/helpers/coolParameters.js
Labels: bug

#3929 [stable29] fix(branding): properly send custom logo to collabora
  src/helpers/coolParameters.js
Labels: bug

#3931 [stable27] fix(branding): properly send custom logo to collabora
  src/helpers/coolParameters.js
Labels: bug

#3898 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3669 fix: Bring back federated editing in viewer iframe
  .github/workflows/cypress-e2e.yml
  appinfo/routes.php
  cypress/e2e/direct.spec.js
  cypress/e2e/integration.spec.js
  cypress/e2e/share-federated.spec.js
  cypress/support/commands.js
  lib/Controller/DocumentController.php
  lib/Service/FederationService.php
  src/helpers/coolParameters.js
  src/view/Office.vue
Labels: bug, 3. to review, backport-request

#3944 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#3806 feat: implement PdfService using mikehaertl/php-pdftk
  appinfo/routes.php
  composer/composer.json
  composer/composer.lock
  composer/composer/autoload_classmap.php
  composer/composer/autoload_psr4.php
  composer/composer/autoload_real.php
  composer/composer/autoload_static.php
  composer/composer/installed.json
  composer/composer/installed.php
  composer/composer/platform_check.php
  composer/mikehaertl/php-pdftk/.github/workflows/tests.yml
  composer/mikehaertl/php-pdftk/LICENSE
  composer/mikehaertl/php-pdftk/README.md
  composer/mikehaertl/php-pdftk/composer.json
  composer/mikehaertl/php-pdftk/src/Command.php
  composer/mikehaertl/php-pdftk/src/DataFields.php
  composer/mikehaertl/php-pdftk/src/FdfFile.php
  composer/mikehaertl/php-pdftk/src/InfoFields.php
  composer/mikehaertl/php-pdftk/src/InfoFile.php
  composer/mikehaertl/php-pdftk/src/Pdf.php
  composer/mikehaertl/php-pdftk/src/XfdfFile.php
  composer/mikehaertl/php-shellcommand/.github/workflows/tests.yml
  composer/mikehaertl/php-shellcommand/CHANGELOG.md
  composer/mikehaertl/php-shellcommand/LICENSE
  composer/mikehaertl/php-shellcommand/README.md
  composer/mikehaertl/php-shellcommand/composer.json
  composer/mikehaertl/php-shellcommand/src/Command.php
  composer/mikehaertl/php-tmpfile/.github/workflows/tests.yml
  composer/mikehaertl/php-tmpfile/LICENSE
  composer/mikehaertl/php-tmpfile/README.md
  composer/mikehaertl/php-tmpfile/composer.json
  composer/mikehaertl/php-tmpfile/src/File.php
  lib/Controller/TemplateFieldController.php
  lib/Service/PdfService.php
  lib/Service/TemplateFieldService.php
  psalm.xml
Labels: 3. to review

#3949 fix: Fix missing conflicts on pdf templating
  lib/Service/TemplateFieldService.php
Labels: bug, 3. to review

#3948 fix: Do not set a guest name on actual users
  lib/TokenManager.php
Labels: bug, 3. to review

#3919 Pass data to field depending on field type
  composer.lock
  cypress/e2e/templates.spec.js
  cypress/fixtures/templates/document_template_with_fields.odt
  cypress/support/commands.js
  lib/Service/PdfService.php
  lib/Service/TemplateFieldService.php
Labels: enhancement, 2. developing, php

#3956 fix: Catch InvalidFieldTypeException
  lib/Service/TemplateFieldService.php
Labels: bug, 3. to review

#3958 fix: Check for mimetype before processing new file from template
  lib/Listener/FileCreatedFromTemplateListener.php
Labels: bug, 3. to review
