Repository nextcloud/richdocuments, pull requests merged in 2025-05, with the labels that each got.

#4719 test: skip remote link reshare test
  cypress/e2e/share-federated.spec.js
Labels: 3. to review

#4722 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4724 [stable31] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4723 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4730 fix(setting-iframe): move iframe to bottom and set height to 2000px
  src/components/AdminSettings.vue
  src/components/CoolFrame.vue
  src/components/PersonalSettings.vue
Labels: bug, design

#4714 fix: do not fetch remote collabora url for own server
  lib/Service/FederationService.php
  tests/lib/Service/FederationServiceTest.php
Labels: 2. developing, backport-request

#4712 fix(Wopi): fall back to super share if share token is not available
  lib/Controller/AssetsController.php
  lib/Controller/WopiController.php
  lib/Helper.php
  lib/Listener/BeforeFetchPreviewListener.php
  lib/TokenManager.php
Labels: bug, 2. developing

#4739 Fix save as on mobile with direct editing
  cypress/e2e/direct.spec.js
  src/document.js
Labels: bug, 3. to review, backport-request

#4390 Slide deck generation task provider
  lib/AppInfo/Application.php
  lib/Service/RemoteService.php
  lib/Service/SlideDeckService.php
  lib/Service/TemplateFieldService.php
  lib/TaskProcessing/SlideDeckGenerationProvider.php
  lib/TaskProcessing/SlideDeckGenerationTaskType.php
Labels: enhancement, 2. developing, feature: templates

#4744 chore: release v8.4.12
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, release

#4745 chore: release v8.5.7
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, release

#4746 chore: release v8.6.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, release

#4770 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4769 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4768 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4780 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4779 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4782 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4788 chore: remove dropped deprecated method call for share manager
  lib/Controller/DirectViewController.php
  lib/Controller/DocumentController.php
  lib/Controller/DocumentTrait.php
  lib/Controller/FederationController.php
  lib/Controller/OCSController.php
  lib/Controller/WopiController.php
  lib/Service/FederationService.php
  tests/psalm-baseline.xml
Labels: bug, 3. to review

#4787 fix(CoolFrame): Init and accept postMessage for setting iframe height
  src/components/CoolFrame.vue
Labels: backport-request

#4698 fix: Ensure edit permissions are checked before template file token generation
  lib/TokenManager.php
Labels: bug, 2. developing, feedback-requested

#4781 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4804 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4802 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4713 fix: check if template fields should be extracted
  cypress/e2e/templates.spec.js
  lib/Listener/BeforeGetTemplatesListener.php
Labels: 3. to review, backport-request, php, javascript, performance 🚀, feature: templates

#4657 feat(setting): add dark/light iframe CSS vars
  src/components/CoolFrame.vue
  src/helpers/coolParameters.js
Labels: backport-request, feedback-requested

#4815 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
