Repository nextcloud/richdocuments, pull requests merged in 2025-04, with the labels that each got.

#4635 fix: remove composer files
  composer/composer.json
  composer/composer.lock
  composer/composer/InstalledVersions.php
  composer/composer/autoload_classmap.php
  composer/composer/autoload_psr4.php
  composer/composer/autoload_real.php
  composer/composer/autoload_static.php
  composer/composer/installed.json
  composer/composer/installed.php
Labels: 3. to review

#4660 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4658 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4665 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4653 fix(setting): userId undefined issue for template
  lib/Controller/SettingsController.php
Labels: backport-request

#4662 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4664 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4661 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4624 fix(settings): send ui_theme input to cool settings iframe
  src/components/CoolFrame.vue
  src/helpers/coolParameters.js
Labels: bug, backport-request

#4669 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4659 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4676 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4678 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4672 fix: accepted global templates file types
  src/components/AdminSettings/GlobalTemplates.vue
Labels: 3. to review, backport-request

#4677 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4680 feat: load viewer componenty asynchronously to reduce file size
  src/viewer.js
Labels: 2. developing

#4671 fix: load `wopi_callback_url` from initial state into config service
  src/services/config.tsx
Labels: 3. to review, backport-request

#4689 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4692 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4690 [stable31] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4693 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4688 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4691 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4708 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4651 ci: unskip 'Save as' test
  cypress/e2e/integration.spec.js
Labels: feedback-requested

#4711 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4697 fix(iframe): send language to Cool iframe for translation
  src/components/CoolFrame.vue
Labels: bug, 3. to review

#4706 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4707 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
