Repository nextcloud/richdocuments, pull requests merged in 2025-02, with the labels that each got.

#4437 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4438 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4442 fix: portable document format --> pdf
  lib/Conversion/ConversionProvider.php
Labels: 3. to review, backport-request

#4443 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#4373 feat(settings): add admin & user setting iframe
  appinfo/routes.php
  lib/Controller/SettingsController.php
  lib/Controller/WopiController.php
  lib/Db/Wopi.php
  lib/Db/WopiMapper.php
  lib/Helper.php
  lib/Service/CapabilitiesService.php
  lib/Service/SettingsService.php
  lib/Settings/Admin.php
  lib/Settings/Personal.php
  lib/WOPI/SettingsUrl.php
  src/components/AdminSettings.vue
  src/components/CoolFrame.vue
  src/components/PersonalSettings.vue
  src/helpers/url.js
Labels: enhancement, 2. developing, feedback-requested

#4459 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4460 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4467 [stable29] refactor: remove composer files
  .github/workflows/autoloader.yml
  .github/workflows/cypress.yml
  composer.json
  composer/autoload.php
  composer/composer/ClassLoader.php
  composer/composer/LICENSE
  composer/composer/autoload_namespaces.php
  krankerl.toml
Labels: 3. to review

#4469 [stable27] fix: get storage from file instead of parent
  lib/Controller/WopiController.php
Labels: 3. to review

#4488 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4489 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4496 chore: v8.2.16
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4492 [stable31] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4499 chore: release v8.6.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4501 chore: remove `vendor/` from `.nextcloudignore`
  .nextcloudignore
Labels: backport-request

#4515 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4516 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4520 fix(test): fix verify document open in notebookbar
  cypress/e2e/open.spec.js
  cypress/support/commands.js
Labels: 3. to review, backport-request

#4493 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4518 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4522 feat: show presentation template in masterslides
  lib/Controller/SettingsController.php
  lib/Service/SettingsService.php
  lib/TemplateManager.php
Labels: enhancement, 3. to review

#4458 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4463 templates: better support cross-format templates
  lib/Listener/FileCreatedFromTemplateListener.php
  lib/Service/TemplateFieldService.php
Labels: bug, 4. to release, backport-request, feedback-requested

#4471 feat: do not send logo css if value not provided
  src/helpers/coolParameters.js
Labels: 3. to review, backport-request

#4448 feat(test): add tests for template fields with empty labels
  cypress/e2e/templates.spec.js
  cypress/fixtures/templates/document_template_with_fields.odt
  cypress/support/commands.js
Labels: 3. to review, backport-request, javascript, tests, feature: templates
