Repository nextcloud/richdocuments, pull requests merged in 2025-03, with the labels that each got.

#4491 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4549 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4548 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4540 fix(settings): enable UserSettings wopi response
  lib/Controller/WopiController.php
  lib/Middleware/WOPIMiddleware.php
Labels: bug, 3. to review

#4553 ci: Skip save as test until upstream bug is fixed
  cypress/e2e/integration.spec.js
Labels: 3. to review, tests

#4570 chore: update actions/cache
  .github/workflows/cypress-e2e.yml
Labels: 3. to review, backport-request

#4560 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4561 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4567 Properly handle editor user id for direct editing links
  .github/workflows/cypress-e2e.yml
  composer.lock
  lib/Controller/DocumentController.php
  lib/Controller/WopiController.php
  lib/TokenManager.php
  tests/features/direct.feature
Labels: bug, 3. to review, backport-request

#4559 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4556 fix(token): reduce token generation for settings files
  lib/Controller/WopiController.php
  lib/Service/SettingsService.php
Labels: bug, 3. to review

#4521 fix(settings): accept settings URL from discovery endpoint
  lib/Settings/Admin.php
  lib/Settings/Personal.php
  lib/TokenManager.php
  src/components/AdminSettings.vue
  src/components/CoolFrame.vue
  src/components/PersonalSettings.vue
  src/helpers/url.js
Labels: bug, 3. to review, feedback-requested

#4581 fix(federation): properly encode file names
  cypress/e2e/share-federated.spec.js
  cypress/fixtures/next % cloud.odt
  cypress/fixtures/next & cloud.odt
  lib/Service/FederationService.php
Labels: 3. to review, backport-request

#4426 Config option to disable previews
  docs/app_settings.md
  lib/AppConfig.php
  lib/Preview/Office.php
  tests/lib/AppConfigTest.php
  tests/lib/Listener/AddContentSecurityPolicyListenerTest.php
Labels: enhancement, 3. to review

#4592 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4591 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4593 [stable31] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4590 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4604 chore: Bump github actions from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  REUSE.toml
  psalm.xml
Labels: dependencies

#4605 chore: Bump github actions from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  REUSE.toml
  psalm.xml
Labels: dependencies

#4606 Ensure we have a clean db schema when migrating
  lib/Migration/Version2060Date20200302131958.php
Labels: bug

#4613 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4615 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4616 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4617 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4614 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4631 feat: add composer install to readme
  README.md
Labels: 3. to review, documentation

#4618 [stable31] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4644 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4645 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4646 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4648 chore: release v8.6.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#4649 chore: release v8.5.6
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
