Repository nextcloud/richdocuments, pull requests merged in 2025-10, with the labels that each got.

#5057 chore(release): v8.4.13
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5068 [stable32] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5067 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5066 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5073 chore: update to php8.2
  .github/workflows/cypress-e2e.yml
  .github/workflows/integration.yml
  composer.json
  psalm.xml
Labels: 3. to review

#5078 fix(workflow): run cypress on stable32 server version
  .github/workflows/cypress-e2e.yml
Labels: 3. to review

#5058 fix(SecureView): node cannot be found when within groupfolder
  lib/PermissionManager.php
  lib/Storage/SecureViewWrapper.php
Labels: bug, 3. to review, backport-request
