Repository nextcloud/richdocuments, pull requests merged in 2025-09, with the labels that each got.

#4981 [stable31] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4979 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4980 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4950 chore(workflows): add stable32 branch to workflows
  .github/workflows/npm-audit-fix.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#4983 fix: register handler within init script
  lib/Listener/LoadViewerListener.php
  lib/Listener/ShareLinkListener.php
  package-lock.json
  package.json
  src/init-viewer.js
  src/viewer.js
  webpack.js
Labels: bug, 3. to review

#4984 fix: prevent error when send null to json_decode
  lib/Service/CapabilitiesService.php
Labels: backport-request

#5010 fix(SecureView): do not rely on specualtive getMountPoint()
  lib/Storage/SecureViewWrapper.php
Labels: 3. to review, 2. developing, backport-request

#5020 chore(release): prepare for new beta release
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5021 fix(Templates): like MS docs, also include OpenDocument docs in templates
  lib/TemplateManager.php
Labels: bug, 3. to review, backport-request

#5032 fix(test): failing integration spec tests
  cypress/e2e/integration.spec.js
  src/view/Office.vue
Labels: bug, 3. to review, javascript, tests

#5037 chore(release): v8.7.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5046 fix(test): adjust selectors
  cypress/e2e/templates.spec.js
Labels: 3. to review

#5050 chore(release): v9.0.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5014 [stable32] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5031 [stable32] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5016 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5053 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
