Repository nextcloud/richdocuments, pull requests merged in 2025-06, with the labels that each got.

#4818 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4825 fix(tests): use `autoload.php` for unit tests
  tests/bootstrap.php
Labels: 3. to review, backport-request

#4819 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4814 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4809 [stable30] fix: for shares allow document creation only for users that ca…
  src/public.js
Labels: bug, 3. to review, backport-request

#4834 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4835 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4833 chore: remove reviewers from dependabot config
  .github/dependabot.yml
Labels: 3. to review

#4831 fix(shares): guest users inherit edit_group
  lib/Listener/ShareLinkListener.php
  lib/Service/InitialStateService.php
  src/public.js
Labels: 3. to review, backport-request

#4840 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4843 feat(ai): spreadsheet conversion input filters
  lib/Service/DocumentGenerationService.php
  lib/Service/RemoteService.php
Labels: 3. to review

#4848 Show statusbar by default for all doc types
  src/helpers/coolParameters.js
Labels: backport-request

#4857 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4856 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4855 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4866 fix: undefined share for preview
  lib/Listener/BeforeFetchPreviewListener.php
Labels: 3. to review, backport-request
